cap lab var start "start of interview date and time"
cap lab var end "end of interview date and time"
cap lab var hhid "Enter hhid of the household you plan to survey"
cap lab var sfprovince "Pre-filled: Province"
cap lab var sfdistrict "Pre-filled: District"
cap lab var sfcdc "Pre-filled: CDC"
cap lab var sfvillage "Pre-filled: Village"
cap lab var sfcbsg_resp "Pre-filled: Name of CBSG member/respondent"
cap lab var sfcbsg "Pre-filled: Name of CBSG"
cap lab var sfnumber1 "Pre-filled: Mobile Number"
cap lab var sfnumber2 "Pre-filled: Alt Mobile"
cap lab var sfnumber3 "Pre-filled: Alt Mobile 2"
cap lab var note_hhid "HHID: ${hhid}"
cap lab var note_sfcbsg_resp "CBSG participant: ${sfcbsg_resp}"
cap lab var note_sfprovince "Province: ${sfprovince}"
cap lab var note_sfdistrict "District: ${sfdistrict}"
cap lab var note_sfcdc "CDC: ${sfcdc}"
cap lab var note_sfvillage "Village: ${sfvillage}"
cap lab var note_sfcbsg_name "Name of CBSG: ${sfcbsg}"
cap lab var note_sfnumber1 "Mobile number: ${sfnumber1}"
cap lab var note_sfnumber2 "Alt mobile number: ${sfnumber2}"
cap lab var note_sfnumber3 "2nd Alt mobile number: ${sfnumber3}"
cap lab var enum_name1 "Name of Enumerator for CBSG respondent survey"
cap lab var enum_name2 "Name of Enumerator for MKP survey"
cap lab var Q1ee "Location type"
cap lab var Q1f1 "Field Officer do not read: have you located the household?"
cap lab var Q1f2 "Why not?"
cap lab var Q1f2_other "Other Specify other reason"
cap lab var Q1l_consent "To CBSG respondent: We are a team working with the Aga Khan Foundation and the World Bank. We are working on a project concerned with developing local economies. The results of the survey will be important for helping design programs on local economic development for the People of Afghanistan. I would like to talk to you about this. The interview will take about 90 minutes. All the information we obtain will remain strictly confidential and your answers will never be identified. During the survey, you may refuse to answer any question or discontinue the survey at any time.  Do we have permission to proceed with the interview?"
cap lab var Q1l_whynot "Why not?"
cap lab var Q1l_date "When should we come back?"
cap lab var Q1l_time "What time of day is best?"
cap lab var cdc_ver "Is ${sfcdc} the correct name of this cdc?"
cap lab var cdc_corr "Please write name of CDC, and be careful about spelling"
cap lab var village_ver "Is ${sfvillage} the correct name of this village?"
cap lab var village_corr "Please write name of village, and be careful about spelling"
cap lab var cbsg_ver "Is ${sfcbsg} the correct name of this CBSG?"
cap lab var cbsg_corr "Please write name of CBSG, and be careful about spelling"
cap lab var resp_ver "Is ${sfcbsg_resp} the correct name of this CBSG member?"
cap lab var resp_corr "Please write name of CBSG member/respondent, and be careful about spelling"
cap lab var cbsg_resp "Name of CBSG respondent"
cap lab var cbsg "Name of CBSG that respondent belongs to"
cap lab var Q1m1 "The name of a well known member of your household"
cap lab var Q1m2 "Father's name"
cap lab var Q1m3_0 "Do you have a contact number?"
cap lab var Q1m3 "Mobile number"
cap lab var Q1m4_0 "Does anyone else in your household have a contact number?"
cap lab var Q1m4 "Family member mobile number"
cap lab var Q1m5_0 "Do you have an alternative contact number?"
cap lab var Q1m5 "Alternative mobile number"
cap lab var Q1m_note "You must list at least one phone number for household"
cap lab var Q1n "How many persons currently live in your household?"
cap lab var Q1o "Who is the most knowledgable person (MKP) in your household?"
cap lab var Q1p "What is the relationship of he most knowledgable person (MKP) to you?"
cap lab var Q1p_other "Other (please Specify)?"
cap lab var Q1r1 "Could my colleague, ${enum_name2}, speak to ${Q1o}, while I interview you?"
cap lab var Q1r2 "Why not?"
cap lab var Q1r2_other "Other (please Specify)?"
cap lab var Q1r3 "Is there ANOTHER person in the household who will know about the assets of the household, and the age, education, employment, of every household member, with whom we can speak, and who is CURRENTLY PRESENT?"
cap lab var Q1r4 "What is the name of this individual?"
cap lab var Q1r5 "What is the relationship of ${Q1r4} to you, ${cbsg_resp}?"
cap lab var Q1r5_other "Other (please Specify)?"
cap lab var Q1s01 "Does ${Q1o} have a contact number?"
cap lab var Q1s1 "What is ${Q1o} 's telephone number?"
cap lab var Q1s02 "Does ${Q1r4} have a contact number?"
cap lab var Q1s2 "What is ${Q1r4} 's telephone number?"
cap lab var Q1t_date "When will ${Q1o} be back?"
cap lab var Q1t_time "What time of day is best?"
cap lab var note1 "We would like to start with some information about the people who usually live and sleep in this household, starting with the head of the household. Please mention all people who usually stay here, including babies and infants, and people who are not immediate kin."
cap lab var note2 "A household is defined as a group of people who normally live together and eat meals together, and have been doing so for at least 6 of the 12 months preceding the interview. Therefore, a member of your household is defined on the basis of the usual place of residence, and short term guests are not included. PLEASE NOTE that in this list, The following categories of people are considered as household members even though they have lived for less than 6 months in the past 12 months: (i) Infants who are less than 6 months old (ii) Newly married who have been living together for less than 6 months (iii) Students and seasonal workers who have not been living in or as part of another household, and (iv) Other persons living together for less than 6 months but who are expected to live in the household permanently (or for a longer duration). Servants, farm workers and other such individuals who live and take meals with the household are to be identified as household members, even though they may not have blood relationship with the respondent."
cap lab var Q2a "According to this definition of a household, how many individuals live in the household?"
cap lab var members "Roster 1: List of members"
cap lab var Q2_memberid "ID for household member"

forv i = 1/27 {
	cap lab var Q2b_`i' "Name of household member `i'"
}

cap lab var Q2c "Is this member usually present in the household (and not part of another household)?"
cap lab var Q2c_other "Other (please Specify)?"
cap lab var Q2d "What is ${Q2b}'s age in completed years?"
cap lab var Q2c_month "What is ${Q2b}'s age in completed Months?"
cap lab var members "Roster 1 hh members"
cap lab var det "Roster 2"
cap lab var roster2_res "Roster residents"
cap lab var rost2 "Roster 2: Details"
cap lab var roster2_name "Roster2 name"
cap lab var roster2_age "Roster2 age"
cap lab var roster2note "I will now ask you a questions about ${roster2_name}, age ${roster2_age}"

forv i = 1/27 {
	cap lab var Q2g_`i' "What is the relationship of ${roster2_name_`i'} to you?"
}

cap lab var Q2g_other "Other (please Specify)?"
cap lab var Q2h "Is ${roster2_name} male or female?"
cap lab var Q2i "What is the marital status of ${roster2_name}?"
cap lab var Q2j "Does ${roster2_name} have a tazkira?"
cap lab var Q2k1 "Did ${roster2_name} reside outside of the home for more than 3 months of the past 12 months?"
cap lab var Q2k2 "Where does ${roster2_name} go?"
cap lab var Q2k2_other "Other (please Specify)?"

forv i = 1/27 {
	cap lab var Q2l_`i' "Can ${roster2_name_`i'} read and write?"
}

cap lab var Q2m "Did ${roster2_name} ever attend formal school? (including formal Islamic school)"

forv i = 1/27 {
	cap lab var Q2n1_`i' "What is the highest grade in which ${roster2_name_`i'} was enrolled?"
}

cap lab var Q2n1_error "You stated that ${roster2_name} never attended school, but then indicated that ${roster2_name} attended some schooling in the next question. Please clarify"

forv i = 1/27 {
	cap lab var Q2n2_`i' "Enter highest grade level COMPLETED"
}

cap lab var Q2q "In the past SEVEN DAYS how many TOTAL HOURS did ${roster2_name} work on household chores, or tending to children, cooking, fetching water, or other household chores?"
cap lab var Q2r "In the past SEVEN DAYS, did ${roster2_name} do any work for pay, for profit, or for family gain, INCLUDING farm work or tending livestock, or poultry, or any occasional work, EVEN for one hour?"
cap lab var Q2s "Although ${roster2_name} did not work last week, does he/she have work from which he/she was temporarily absent?"
cap lab var Q2t "What are the main reasons that ${roster2_name} did not work in the last seven days?"
cap lab var Q2u "What kinds of work (paid or unpaid) was ${roster2_name}'s biggest sources of income over the past 12 MONTHS (Select all that apply in the past 12 MONTHS, up to 3)"
cap lab var Q2u_other "Other (please Specify)?"
cap lab var Q2v "What is the total amount in cash, services or goods ${roster2_name} received for ALL OF THESE economic activities in the last 30 DAYS, if any? (in case of cash include any bonuses, commissions, allowances or tips)"
cap lab var rost_act "Roster activities"
cap lab var Q2_roster_act_id "Roster activity ID"
cap lab var Q2_roster_act_name "Roster activity label"
cap lab var Q2w1 "I will now ask you 5 questions about (${Q2_roster_act_name}), the activity that you mentioned above. How many DAYS did ${roster2_name} work in this activity during the past SEVEN DAYS?"
cap lab var Q2w2 "How many actual HOURS PER DAY, on average, did ${roster2_name} work on average on this activity  (${Q2_roster_act_name}) during the past SEVEN DAYS?"
cap lab var Q2w3 "Did ${roster2_name}'s work on this activity  (${Q2_roster_act_name}) take place INSIDE the household or household land?"
cap lab var Q2w4 "Did ${roster2_name} receive any payment in cash or in-kind for their work on ${Q2_roster_act_name}"
cap lab var Q2w5 "What is ${roster2_name} relationship's with this employer for their work in (${Q2_roster_act_name})?"
cap lab var Q2w5_other "Other (please Specify)?"
cap lab var rost2 "Roster 2 questions"
cap lab var Q2_estimate "Please estimate the total income for your entire household combined over the last 30 DAYS"
cap lab var Q2x_note "In the past 12 MONTHS, how much has your household received from the following sources"
cap lab var Q2x1 "remittances from those who do not live in the household?"
cap lab var Q2x2 "income from lending funds to others?"
cap lab var Q2x3 "rental income?"
cap lab var Q2x4 "income from pensions?"
cap lab var Q2x5 "income from zakat?"
cap lab var Q2x6 "other income not yet discussed?"
cap lab var roster2_name1 "Roster2 name1"
cap lab var roster2_name2 "Roster2 name2"
cap lab var roster2_name3 "Roster2 name3"
cap lab var roster2_name4 "Roster2 name4"
cap lab var roster2_name5 "Roster2 name5"
cap lab var roster2_name6 "Roster2 name6"
cap lab var roster2_name7 "Roster2 name7"
cap lab var roster2_name8 "Roster2 name8"
cap lab var roster2_name9 "Roster2 name9"
cap lab var roster2_name10 "Roster2 name10"
cap lab var roster2_name11 "Roster2 name11"
cap lab var roster2_name12 "Roster2 name12"
cap lab var roster2_name13 "Roster2 name13"
cap lab var roster2_name14 "Roster2 name14"
cap lab var roster2_name15 "Roster2 name15"
cap lab var roster2_name16 "Roster2 name16"
cap lab var roster2_name17 "Roster2 name17"
cap lab var roster2_name18 "Roster2 name18"
cap lab var roster2_name19 "Roster2 name19"
cap lab var roster2_name20 "Roster2 name20"
cap lab var roster2_age1 "Roster2 name1 age1"
cap lab var roster2_age2 "Roster2 name2 age2"
cap lab var roster2_age3 "Roster2 name3 age3"
cap lab var roster2_age4 "Roster2 name4 age4"
cap lab var roster2_age5 "Roster2 name5 age5"
cap lab var roster2_age6 "Roster2 name6 age6"
cap lab var roster2_age7 "Roster2 name7 age7"
cap lab var roster2_age8 "Roster2 name8 age8"
cap lab var roster2_age9 "Roster2 name9 age9"
cap lab var roster2_age10 "Roster2 name10 age10"
cap lab var roster2_age11 "Roster2 name11 age11"
cap lab var roster2_age12 "Roster2 name12 age12"
cap lab var roster2_age13 "Roster2 name13 age13"
cap lab var roster2_age14 "Roster2 name14 age14"
cap lab var roster2_age15 "Roster2 name15 age15"
cap lab var roster2_age16 "Roster2 name16 age16"
cap lab var roster2_age17 "Roster2 name17 age17"
cap lab var roster2_age18 "Roster2 name18 age18"
cap lab var roster2_age19 "Roster2 name19 age19"
cap lab var roster2_age20 "Roster2 name20 age20"
cap lab var marstatus "What is your marital status?"
cap lab var parstatus "Do you have children?"
cap lab var Q3a0 "I will now ask you a few questions about household decision making"
cap lab var Q3a_list "list of members"
cap lab var Q3a "The head of the household is a person among the group of householders who is regarded/assigned as the head of the household and generally makes decisions in the household. Which individual listed is the head of household?"
cap lab var Q3a_name1 "${roster2_name1}, age ${roster2_age1}"
cap lab var Q3a_name2 "${roster2_name2}, age ${roster2_age2}"
cap lab var Q3a_name3 "${roster2_name3}, age ${roster2_age3}"
cap lab var Q3a_name4 "${roster2_name4}, age ${roster2_age4}"
cap lab var Q3a_name5 "${roster2_name5}, age ${roster2_age5}"
cap lab var Q3a_name6 "${roster2_name6}, age ${roster2_age6}"
cap lab var Q3a_name7 "${roster2_name7}, age ${roster2_age7}"
cap lab var Q3a_name8 "${roster2_name8}, age ${roster2_age8}"
cap lab var Q3a_name9 "${roster2_name9}, age ${roster2_age9}"
cap lab var Q3a_name10 "${roster2_name10}, age ${roster2_age10}"
cap lab var Q3a_name11 "${roster2_name11}, age ${roster2_age11}"
cap lab var Q3a_name12 "${roster2_name12}, age ${roster2_age12}"
cap lab var Q3a_name13 "${roster2_name13}, age ${roster2_age13}"
cap lab var Q3a_name14 "${roster2_name14}, age ${roster2_age14}"
cap lab var Q3a_name15 "${roster2_name15}, age ${roster2_age15}"
cap lab var Q3a_name16 "${roster2_name16}, age ${roster2_age16}"
cap lab var Q3a_name17 "${roster2_name17}, age ${roster2_age17}"
cap lab var Q3a_name18 "${roster2_name18}, age ${roster2_age18}"
cap lab var Q3a_name19 "${roster2_name19}, age ${roster2_age19}"
cap lab var Q3a_name20 "${roster2_name20}, age ${roster2_age20}"
cap lab var Q3b "Does the head of household do any of the following (select all that apply)?"
cap lab var Q3b_other "Other (please Specify)?"
cap lab var Q3c_list "list of members"
cap lab var Q3c "Which individual listed is you?"
cap lab var Q3c_name1 "${roster2_name1}, age ${roster2_age1}"
cap lab var Q3c_name2 "${roster2_name2}, age ${roster2_age2}"
cap lab var Q3c_name3 "${roster2_name3}, age ${roster2_age3}"
cap lab var Q3c_name4 "${roster2_name4}, age ${roster2_age4}"
cap lab var Q3c_name5 "${roster2_name5}, age ${roster2_age5}"
cap lab var Q3c_name6 "${roster2_name6}, age ${roster2_age6}"
cap lab var Q3c_name7 "${roster2_name7}, age ${roster2_age7}"
cap lab var Q3c_name8 "${roster2_name8}, age ${roster2_age8}"
cap lab var Q3c_name9 "${roster2_name9}, age ${roster2_age9}"
cap lab var Q3c_name10 "${roster2_name10}, age ${roster2_age10}"
cap lab var Q3c_name11 "${roster2_name11}, age ${roster2_age11}"
cap lab var Q3c_name12 "${roster2_name12}, age ${roster2_age12}"
cap lab var Q3c_name13 "${roster2_name13}, age ${roster2_age13}"
cap lab var Q3c_name14 "${roster2_name14}, age ${roster2_age14}"
cap lab var Q3c_name15 "${roster2_name15}, age ${roster2_age15}"
cap lab var Q3c_name16 "${roster2_name16}, age ${roster2_age16}"
cap lab var Q3c_name17 "${roster2_name17}, age ${roster2_age17}"
cap lab var Q3c_name18 "${roster2_name18}, age ${roster2_age18}"
cap lab var Q3c_name19 "${roster2_name19}, age ${roster2_age19}"
cap lab var Q3c_name20 "${roster2_name20}, age ${roster2_age20}"
cap lab var Q3d_list "list of members"
cap lab var Q3d "Which individual(s) listed is your spouse?"
cap lab var Q3d_na "Do not have a spouse"
cap lab var Q3d_name1 "${roster2_name1}, age ${roster2_age1}"
cap lab var Q3d_name2 "${roster2_name2}, age ${roster2_age2}"
cap lab var Q3d_name3 "${roster2_name3}, age ${roster2_age3}"
cap lab var Q3d_name4 "${roster2_name4}, age ${roster2_age4}"
cap lab var Q3d_name5 "${roster2_name5}, age ${roster2_age5}"
cap lab var Q3d_name6 "${roster2_name6}, age ${roster2_age6}"
cap lab var Q3d_name7 "${roster2_name7}, age ${roster2_age7}"
cap lab var Q3d_name8 "${roster2_name8}, age ${roster2_age8}"
cap lab var Q3d_name9 "${roster2_name9}, age ${roster2_age9}"
cap lab var Q3d_name10 "${roster2_name10}, age ${roster2_age10}"
cap lab var Q3d_name11 "${roster2_name11}, age ${roster2_age11}"
cap lab var Q3d_name12 "${roster2_name12}, age ${roster2_age12}"
cap lab var Q3d_name13 "${roster2_name13}, age ${roster2_age13}"
cap lab var Q3d_name14 "${roster2_name14}, age ${roster2_age14}"
cap lab var Q3d_name15 "${roster2_name15}, age ${roster2_age15}"
cap lab var Q3d_name16 "${roster2_name16}, age ${roster2_age16}"
cap lab var Q3d_name17 "${roster2_name17}, age ${roster2_age17}"
cap lab var Q3d_name18 "${roster2_name18}, age ${roster2_age18}"
cap lab var Q3d_name19 "${roster2_name19}, age ${roster2_age19}"
cap lab var Q3d_name20 "${roster2_name20}, age ${roster2_age20}"
cap lab var Q3e_list "list of members"
cap lab var Q3e "Which individual(s) listed are your biological children?"
cap lab var Q3e_na "Do not have any children"
cap lab var Q3e_name1 "${roster2_name1}, age ${roster2_age1}"
cap lab var Q3e_name2 "${roster2_name2}, age ${roster2_age2}"
cap lab var Q3e_name3 "${roster2_name3}, age ${roster2_age3}"
cap lab var Q3e_name4 "${roster2_name4}, age ${roster2_age4}"
cap lab var Q3e_name5 "${roster2_name5}, age ${roster2_age5}"
cap lab var Q3e_name6 "${roster2_name6}, age ${roster2_age6}"
cap lab var Q3e_name7 "${roster2_name7}, age ${roster2_age7}"
cap lab var Q3e_name8 "${roster2_name8}, age ${roster2_age8}"
cap lab var Q3e_name9 "${roster2_name9}, age ${roster2_age9}"
cap lab var Q3e_name10 "${roster2_name10}, age ${roster2_age10}"
cap lab var Q3e_name11 "${roster2_name11}, age ${roster2_age11}"
cap lab var Q3e_name12 "${roster2_name12}, age ${roster2_age12}"
cap lab var Q3e_name13 "${roster2_name13}, age ${roster2_age13}"
cap lab var Q3e_name14 "${roster2_name14}, age ${roster2_age14}"
cap lab var Q3e_name15 "${roster2_name15}, age ${roster2_age15}"
cap lab var Q3e_name16 "${roster2_name16}, age ${roster2_age16}"
cap lab var Q3e_name17 "${roster2_name17}, age ${roster2_age17}"
cap lab var Q3e_name18 "${roster2_name18}, age ${roster2_age18}"
cap lab var Q3e_name19 "${roster2_name19}, age ${roster2_age19}"
cap lab var Q3e_name20 "${roster2_name20}, age ${roster2_age20}"
cap lab var Q3f_list "list of members"
cap lab var Q3f "Which individual(s) listed are currently members of any CBSGs?"
cap lab var Q3f_na "No others are members of any CBSG"
cap lab var Q3f_name1 "${roster2_name1}, age ${roster2_age1}"
cap lab var Q3f_name2 "${roster2_name2}, age ${roster2_age2}"
cap lab var Q3f_name3 "${roster2_name3}, age ${roster2_age3}"
cap lab var Q3f_name4 "${roster2_name4}, age ${roster2_age4}"
cap lab var Q3f_name5 "${roster2_name5}, age ${roster2_age5}"
cap lab var Q3f_name6 "${roster2_name6}, age ${roster2_age6}"
cap lab var Q3f_name7 "${roster2_name7}, age ${roster2_age7}"
cap lab var Q3f_name8 "${roster2_name8}, age ${roster2_age8}"
cap lab var Q3f_name9 "${roster2_name9}, age ${roster2_age9}"
cap lab var Q3f_name10 "${roster2_name10}, age ${roster2_age10}"
cap lab var Q3f_name11 "${roster2_name11}, age ${roster2_age11}"
cap lab var Q3f_name12 "${roster2_name12}, age ${roster2_age12}"
cap lab var Q3f_name13 "${roster2_name13}, age ${roster2_age13}"
cap lab var Q3f_name14 "${roster2_name14}, age ${roster2_age14}"
cap lab var Q3f_name15 "${roster2_name15}, age ${roster2_age15}"
cap lab var Q3f_name16 "${roster2_name16}, age ${roster2_age16}"
cap lab var Q3f_name17 "${roster2_name17}, age ${roster2_age17}"
cap lab var Q3f_name18 "${roster2_name18}, age ${roster2_age18}"
cap lab var Q3f_name19 "${roster2_name19}, age ${roster2_age19}"
cap lab var Q3f_name20 "${roster2_name20}, age ${roster2_age20}"
cap lab var Q3g "Who has the final say on Purchasing food for the family of ${cbsg_resp}"
cap lab var Q3h "Who has the final say on Whether the family of ${cbsg_resp} may borrow funds"
cap lab var Q3i "Who has the final say on Purchase of assets that ${cbsg_resp}'s family uses"
cap lab var Q4a "Now, imagine that you have an emergency and you need to pay AFG 2060. How possible is it that you could come up with AFG 2060 within the NEXT MONTH? Is it very possible, somewhat possible, not very possible, or not at all possible?"
cap lab var exp3 "Expenditure past 3 months"
cap lab var Q4b0 "I will now ask you about your family's expenditure. In the past 3 months, how much did your household spend on..."
cap lab var Q4b1 "Health services and medicines"
cap lab var Q4b2 "Tuition for education"
cap lab var Q4b3 "Other education expenses (uniforms, textbooks, school supplies)"
cap lab var exp1 "Expenditure past 1 month"
cap lab var Q4b_1mo_note "In the past month, how much did your household spend on the following categories of items:"
cap lab var Q4b4 "Food at home"
cap lab var Q4b5 "Food away from home"
cap lab var Q4b6 "Grooming, cosmetics, laundry, soap, shampoo (hygiene)"
cap lab var Q4b7 "Housing rent"
cap lab var Q4b8 "Communication (phone & internet)"
cap lab var Q4b9 "Transportation"
cap lab var Q4c "During the last 12 MONTHS did you always have enough food for your household?"
cap lab var Q4d "For how many months in the last 12 months did you not have enough food for your household?"
cap lab var Q4d1 "In the past seven days, has there been any time when your household did not have enough food or money to buy food?"
cap lab var food "Food"
cap lab var Q4d_note "In the past seven days, when you did not have enough food or money…"
cap lab var Q4d2 "HOW OFTEN did anyone in your household have to: rely on less-preferred and less-expensive foods because of lack of resources?"
cap lab var Q4d3 "HOW OFTEN did anyone in your household have to:  limit portion sizes at meal times?"
cap lab var Q4d4 "HOW OFTEN did anyone in your household have to:  restrict consumption by adults in order for small children to eat?"
cap lab var Q4d5 "HOW OFTEN did anyone in your household have to:  skip meals or reduce number of meals eaten by anyone in household?"
cap lab var diet "Diet"
cap lab var Q4e0 "I will now ask you about your family's consumption of the following food groups. How many days in the past 7 days did your entire household eat:"
cap lab var Q4e1 "Cereals (e.g. bread, wheat, rice, maize, pasta, etc.)"
cap lab var Q4e2 "Tubers (e.g. potatoes, sweet potatoes, etc.)"
cap lab var Q4e3 "Pulses and nuts (e.g. beans, lentils, peas, peanuts, etc.)"
cap lab var Q4e4 "Vegetables (e.g. onion, tomato, eggplant, cabbage, etc.)"
cap lab var Q4e5 "Fruits (e.g. water melon, apricots, grapes, raisins, etc.)"
cap lab var Q4e6 "Meat and fish of all types, eggs"
cap lab var Q4e7 "Dairy and dairy products (e.g. milk, yoghurt, krut, dogh, cheese, other milk products)"
cap lab var Q4e8 "Sugar, honey"
cap lab var Q4e9 "Oils, fats"
cap lab var Q5a "What type of dwelling best describes your current dwelling?"
cap lab var Q5a_other "Other (please Specify)?"
cap lab var Q5b "How many years ago was this dwelling constructed?"
cap lab var Q5c "What is the arrangement on the basis of which your household occupies this dwelling"
cap lab var Q5other "Other (please Specify)?"
cap lab var Q5d "If you were to purchase this dwelling today, how much would it cost?"
cap lab var Q5e "What is the distance to this dwelling from the nearest paved road? (in meters)"
cap lab var Q5f1 "Has your household had electricity at any time in the past 30 DAYS from any of these sources: Electric grid or Government generator"
cap lab var Q5f2 "Has your household had electricity at any time in the past 30 DAYS from any of these sources: Private generator"
cap lab var Q5f3 "Has your household had electricity at any time in the past 30 DAYS from any of these sources: Community generator"
cap lab var Q5f4 "Has your household had electricity at any time in the past 30 DAYS from any of these sources: Other sources"
cap lab var Q5g "What is the main source of heating for his house in the winter?"
cap lab var Q5g_other "Other (please Specify)?"
cap lab var Q5h "Which main toilet facility does your household use?"
cap lab var Q5h_other "Other (please Specify)?"
cap lab var Q5i "Is the toilet facility shared with other households?"
cap lab var Q5j "What has been the main source of drinking water for your household in the past 30 days?"
cap lab var Q5j_other "Other (please Specify)?"
cap lab var Q5k "How many minutes does it take to walk, one way, to this main source of water in warm season?"
cap lab var Q5l "What is the main phone service that you use?"
cap lab var Q5l_other "Other (please Specify)?"
cap lab var Q5m1 "Do any of your household members own agricultural land or a garden plot?"
cap lab var Q5m2 "How many Jeribs of agricultural land in total does your household own?"
cap lab var Q5m3 "How many jeribs of irrigated land without garden plot did you or a member of your household own in the most recent spring cultivation season?"
cap lab var Q5m4 "If you were to sell this plot of land today, how much could you sell it for?"
cap lab var Q5m5 "How many jeribs of rain-fed land without garden plot did you or a member of your household own in the most recent spring cultivation season?"
cap lab var Q5m6 "If you were to sell this land today, how much could you sell it for?"
cap lab var Q5m7 "How many jeribs of garden plot did you or a member of your household own in the most recent spring cultivation season?"
cap lab var Q5m8 "If you were to sell this plot of land today, how much could you sell it for?"
cap lab var Q5m9 "Does your household currently own any land or buildings (do not include residential property which your household occupies or agricultural land or property used by your household which was reported above)?"
cap lab var Q5m10 "How much money would your household receive if you sold all this property today?"
cap lab var Q5asset_intro "We will now ask about your household assets and their value"
cap lab var Q5assets "Do you have any of the following assets?"
cap lab var Q5assets_other "Other (please Specify)?"
cap lab var asset "asset repeat"
cap lab var asset_id "asset id"
cap lab var asset_name "asset name"
cap lab var Q5asset1_1 "How many ${asset_name} does your household own today?"
cap lab var Q6a "In the last 7 days, did you work for a wage, salary, commission or any payment in kind; including doing paid domestic work or paid farm work even if for one hour?"
cap lab var Q6b "In the last 7 days, did you run a business of any size for yourself or the household or with partners, even if for one hour?"
cap lab var Q6c "In the last 7 days, did you help in any kind of business run by this household, even if for one hour?"
cap lab var Q6d "In the last 7 days, did you work as a paid or unpaid apprentice even if just for one hour?"
cap lab var Q6e "In the last 7 days, did you work on your household's farm or work with livestock or poultry, even if for one hour?"
cap lab var Q6f "Although you did not work last week, do have work (any of activities above) from which you were temporarily absent?"

*>
cap lab var Q6g1_1 "Were you involved in any of the following economic activities to contribute to earning money for yourself OR YOUR FAMILY in the past 12 months? Agriculture/Farm work/Vegetables/Horticulture"
cap lab var Q6g1_2 "Were you involved in any of the following economic activities to contribute to earning money for yourself OR YOUR FAMILY in the past 12 months? Raising livestock/Poultry/Bees"
cap lab var Q6g1_3 "Were you involved in any of the following economic activities to contribute to earning money for yourself OR YOUR FAMILY in the past 12 months? Wholesale trade/sales"
cap lab var Q6g1_4 "Were you involved in any of the following economic activities to contribute to earning money for yourself OR YOUR FAMILY in the past 12 months? Retail trade/sales (shopkeeping, street sales, market sales)"
cap lab var Q6g1_5 "Were you involved in any of the following economic activities to contribute to earning money for yourself OR YOUR FAMILY in the past 12 months? Food production/processing"
cap lab var Q6g1_6 "Were you involved in any of the following economic activities to contribute to earning money for yourself OR YOUR FAMILY in the past 12 months? Manufacturing (handicrafts, carpets, bricks etc)"
cap lab var Q6g1_7 "Were you involved in any of the following economic activities to contribute to earning money for yourself OR YOUR FAMILY in the past 12 months? Non-agriculture business (sewing, hairdressing,security, repairs, domestic work/child care for others)"
cap lab var Q6g1_8 "Were you involved in any of the following economic activities to contribute to earning money for yourself OR YOUR FAMILY in the past 12 months? Transportation, communication"
cap lab var Q6g1_9 "Were you involved in any of the following economic activities to contribute to earning money for yourself OR YOUR FAMILY in the past 12 months? Household Chores"
cap lab var Q6g1_10 "Were you involved in any of the following economic activities to contribute to earning money for yourself OR YOUR FAMILY in the past 12 months? Mining & Quarrying"
cap lab var Q6g1_11 "Were you involved in any of the following economic activities to contribute to earning money for yourself OR YOUR FAMILY in the past 12 months? Road construction"
cap lab var Q6g1_12 "Were you involved in any of the following economic activities to contribute to earning money for yourself OR YOUR FAMILY in the past 12 months? Construction (e.g. buildings, carpentry)"
cap lab var Q6g1_13 "Were you involved in any of the following economic activities to contribute to earning money for yourself OR YOUR FAMILY in the past 12 months? Health sector"
cap lab var Q6g1_14 "Were you involved in any of the following economic activities to contribute to earning money for yourself OR YOUR FAMILY in the past 12 months? Education sector"
cap lab var Q6g1_15 "Were you involved in any of the following economic activities to contribute to earning money for yourself OR YOUR FAMILY in the past 12 months? Finance sector (Banks, MFIs)"
cap lab var Q6g1_16 "Were you involved in any of the following economic activities to contribute to earning money for yourself OR YOUR FAMILY in the past 12 months? Public administration / Government"
cap lab var Q6g1_17 "Were you involved in any of the following economic activities to contribute to earning money for yourself OR YOUR FAMILY in the past 12 months? NGO program"
cap lab var Q6g1_96 "Were you involved in any of the following economic activities to contribute to earning money for yourself OR YOUR FAMILY in the past 12 months? Other"
*<

cap lab var Q6g2 "Please specify"
cap lab var act "Economic Activities"
cap lab var activity_id "activity id"
cap lab var activity_name "activity name"
cap lab var act_note "I will now ask you several questions about ${activity_name}"
cap lab var Q6h1 "What is your relationship with this employer (for ${activity_name})?"
cap lab var Q6h1_other "Other Specify"
cap lab var Q6i "Did this activity (${activity_name}) take place inside the household or household land?"
cap lab var Q6j_note "For how long have you been engaged in this activity (${activity_name})?"
cap lab var Q6j1 "Years"
cap lab var Q6j2 "Months"
cap lab var Q6k1 "How many days did you work in this activity during the past 30 days?"
cap lab var Q6k2 "How many hours per day, on average, did <name> work on this activity during the past 30 days?"
cap lab var Q6k2_calc "hours in last week"
cap lab var Q6k2_check "We estimate that you worked ${Q6k2_calc} hours in the past 30 days. Does this sound correct?"
cap lab var Q6k2_error "Enumerator, please go back and check"

*>
cap lab var Q6k3_1 "In which seasons do you undertake this activity ${activity_name} generally? winter"
cap lab var Q6k3_2 "In which seasons do you undertake this activity ${activity_name} generally? spring"
cap lab var Q6k3_3 "In which seasons do you undertake this activity ${activity_name} generally? summer"
cap lab var Q6k3_4 "In which seasons do you undertake this activity ${activity_name} generally? fall"
cap lab var Q6k3_98 "In which seasons do you undertake this activity ${activity_name} generally? Do not know"
cap lab var Q6k3_99 "In which seasons do you undertake this activity ${activity_name} generally? Refuse to answer"
*<

cap lab var Q6k4 "How frequently do you receive income for your work (on ${activity_name} )? Daily, weekly, biweekly, monthly, or upon sale of product?"
cap lab var Q6k5 "On average, how much do you receive in one installment"
cap lab var Q6k6 "How much did you receive  for your work in ${activity_name} over the past 30 DAYS (revenue-expenses)?"
cap lab var Q6k7 "For enumerator (Do Not Read): How confident was respondent in estimating earnings?"
cap lab var Q6k8 "In addition to any monetary earnings, did you receive any other types of gains from working in the past 30 DAYS (in-kind, bartering, exchange-work) for (${activity_name} )?"
cap lab var Q6k9 "Please estimate the monetary value of these in-kind/barter/exchange labor gains from working over the PAST 30 DAYS"

*>
cap lab var Q6k10_1 "Who usually decides how the earnings from ${activity_name} will be used? Self"
cap lab var Q6k10_2 "Who usually decides how the earnings from ${activity_name} will be used? Partner/Spouse"
cap lab var Q6k10_3 "Who usually decides how the earnings from ${activity_name} will be used? Other Male HH Member"
cap lab var Q6k10_4 "Who usually decides how the earnings from ${activity_name} Other Female HH Member"
cap lab var Q6k10_5 "Who usually decides how the earnings from ${activity_name} Other non-HH member"
cap lab var Q6k10_98 "Who usually decides how the earnings from ${activity_name} Do not know"
cap lab var Q6k10_99 "Who usually decides how the earnings from ${activity_name} Refuse to answer"
*<

cap lab var Q6m "Have you received any training in the past 12 months related to this activity (${activity_name})?"
cap lab var bus_only "bus_only"
cap lab var Q6n1 "Do you employ others in this activity (${activity_name})?"
cap lab var Q6n2 "How many people do you employ (including household members), whether paid or unpaid, on (${activity_name})?"
cap lab var Q6n3 "How many of these people are paid?"
cap lab var Q6n4 "How many hours does the average PAID person work per week"
cap lab var Q6n5 "How much are they paid per hour on average?"
cap lab var Q6n6 "Do any other household member work in this activity (both paid and unpaid)?"
cap lab var Q6n7 "How many male household members work in this activity (both paid and unpaid)?"
cap lab var Q6n8 "How many female household members work in this activity (both paid and unpaid)?"
cap lab var Q6n9 "Total paid in labor costs"
cap lab var Q6o0 "We estimate that you paid around Af ${Q6n9} for labor costs over the past 30 days. Does this sound correct?"
cap lab var Q6o0_note "Enumerator, go back and confirm responses on labor costs"
cap lab var Q6o1 "Over the past 30 days, how much did you and your household spend on the MATERIAL INPUTS required for this activity (${activity_name})"
cap lab var Q6o2 "Over the past 30 days, how much did you and your household spend on the EQUIPMENT required for this activity (${activity_name})"
cap lab var Q6o3 "Over the past 30 days, how much did you and your household spend on the STORAGE, STORE RENTAL, UTILITIES required for this activity (${activity_name})"
cap lab var Q6o4_calc "Total cost of inputs over past month"
cap lab var Q6o5 "We estimate that you paid Af ${Q6o4_calc} for your business (on (${activity_name}) over the past month. Does this sound correct?"
cap lab var Q6o5_note "Enumerator, go back and confirm responses on non-labor costs"
cap lab var Q6p "Who must approve major decisions for this particular activity, such as purchases of materials and equipment?"
cap lab var Q6q "Which assets do you currently use for this activity (${activity_name})"
cap lab var Q6q_other "Do you have other assets that you currently use for this activity? Please list"
cap lab var Q6s "What durable assets (that you do not have) would allow you to expand your productivity in this activity?"
cap lab var Q6s_other "Are there OTHER durable assets that you do not have that would allow you to EXPAND your productivity in this activity? Please list"

*>
cap lab var Q6t1_1 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? Wheat"
cap lab var Q6t1_2 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? Paddy"
cap lab var Q6t1_3 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? Millets"
cap lab var Q6t1_4 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? Mustard"
cap lab var Q6t1_5 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? Opium"
cap lab var Q6t1_6 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? Hashish"
cap lab var Q6t1_7 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? Potato"
cap lab var Q6t1_8 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? Onion"
cap lab var Q6t1_9 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? Chillies"
cap lab var Q6t1_10 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? Tomato"
cap lab var Q6t1_11 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? Cauliflower"
cap lab var Q6t1_12 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? Brinjal"
cap lab var Q6t1_13 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? Cabbage"
cap lab var Q6t1_14 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? Mushroom"
cap lab var Q6t1_15 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? Spinach"
cap lab var Q6t1_16 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? carrot"
cap lab var Q6t1_17 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? bean"
cap lab var Q6t1_18 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? Graham"
cap lab var Q6t1_19 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? Almonds"
cap lab var Q6t1_20 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? Apple"
cap lab var Q6t1_21 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? Apricoat"
cap lab var Q6t1_22 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? Pistachio"
cap lab var Q6t1_23 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? Walnuts"
cap lab var Q6t1_24 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? Grapes"
cap lab var Q6t1_25 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? Figs"
cap lab var Q6t1_26 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? Peach"
cap lab var Q6t1_27 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? Cherry"
cap lab var Q6t1_28 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? Berries"
cap lab var Q6t1_29 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? Pear"
cap lab var Q6t1_30 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? Pomegranate"
cap lab var Q6t1_96 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? Other crops, please specify"
cap lab var Q6t1_99 "What were the 3 products you developed with the highest earnings for the household (in Agriculture/Farm work/Vegetables/Horticulture)? Refuse to answer"
*<

*>
cap lab var Q6t2_ "What were the 3 products you developed with the highest earnings for the household (in Raising livestock/Poultry/Bees)? "
cap lab var Q6t2_1 "What were the 3 products you developed with the highest earnings for the household (in Raising livestock/Poultry/Bees)? Milk"
cap lab var Q6t_2 "What were the 3 products you developed with the highest earnings for the household (in Raising livestock/Poultry/Bees)? Eggs"
cap lab var Q6t_3 "What were the 3 products you developed with the highest earnings for the household (in Raising livestock/Poultry/Bees)? Honey"
cap lab var Q6t_4 "What were the 3 products you developed with the highest earnings for the household (in Raising livestock/Poultry/Bees)? Wool"
cap lab var Q6t_5 "What were the 3 products you developed with the highest earnings for the household (in Raising livestock/Poultry/Bees)? Meat: Cattle"
cap lab var Q6t_6 "What were the 3 products you developed with the highest earnings for the household (in Raising livestock/Poultry/Bees)? Meat: Oxen"
cap lab var Q6t_7 "What were the 3 products you developed with the highest earnings for the household (in Raising livestock/Poultry/Bees)? Meat: Chicken"
cap lab var Q6t_8 "What were the 3 products you developed with the highest earnings for the household (in Raising livestock/Poultry/Bees)? Meat: Turkey"
cap lab var Q6t_9 "What were the 3 products you developed with the highest earnings for the household (in Raising livestock/Poultry/Bees)? Meat: Goat"
cap lab var Q6t_10 "What were the 3 products you developed with the highest earnings for the household (in Raising livestock/Poultry/Bees)? Leather/Skin"
cap lab var Q6t_11 "What were the 3 products you developed with the highest earnings for the household (in Raising livestock/Poultry/Bees)? Live animal: Cattle"
cap lab var Q6t_12 "What were the 3 products you developed with the highest earnings for the household (in Raising livestock/Poultry/Bees)? Live animal: Oxen"
cap lab var Q6t_13 "What were the 3 products you developed with the highest earnings for the household (in Raising livestock/Poultry/Bees)? Live animal: Horses"
cap lab var Q6t_14 "What were the 3 products you developed with the highest earnings for the household (in Raising livestock/Poultry/Bees)? Live animal: Donkeys"
cap lab var Q6t_15 "What were the 3 products you developed with the highest earnings for the household (in Raising livestock/Poultry/Bees)? Live animal: Camels"
cap lab var Q6t_16 "What were the 3 products you developed with the highest earnings for the household (in Raising livestock/Poultry/Bees)? Live animal: Goats"
cap lab var Q6t_17 "What were the 3 products you developed with the highest earnings for the household (in Raising livestock/Poultry/Bees)? Live animal: Sheep"
cap lab var Q6t_18 "What were the 3 products you developed with the highest earnings for the household (in Raising livestock/Poultry/Bees)? Live animal: Chickens"
cap lab var Q6t_19 "What were the 3 products you developed with the highest earnings for the household (in Raising livestock/Poultry/Bees)? Live animal: Turkeys"
cap lab var Q6t_96 "What were the 3 products you developed with the highest earnings for the household (in Raising livestock/Poultry/Bees)? Other livestock product"
cap lab var Q6t_99 "What were the 3 products you developed with the highest earnings for the household (in Raising livestock/Poultry/Bees)? Refuse to answer"
*<

cap lab var Q6t3 "What were the 3 products you developed with the highest earnings for the household (in Wholesale trade/sales)?"
cap lab var Q6t4 "What were the 3 products you developed with the highest earnings for the household (in Retail trade/sales) (shopkeeping, street sales, market sales))?"
cap lab var Q6t5 "What were the 3 products you developed with the highest earnings for the household (in Food production/processing)?"
cap lab var Q6t6 "What were the 3 products you developed with the highest earnings for the household (in Manufacturing (handicrafts, carpets, bricks etc))?"
cap lab var Q6t7 "What were the 3 most products you developed with the highest earnings for the household (in Non-agriculture business (sewing, hairdressing,security, repairs, domestic work/child care for others))?"
cap lab var Q6t8 "What were the 3 products you developed with the highest earnings for the household (in Transportation, communication)?"
cap lab var Q6t_other "What other products did you develop?"
cap lab var prod1 "Product details"
cap lab var prodid1 "product id"
cap lab var prodname1_oth "You selected "Other" product from your agricultural activities. Please specify."
cap lab var prodname1_reg "product label if selected from list"
cap lab var prodname1 "product label"
cap lab var inv1 "inventory"
cap lab var inventorynote1 "Q6u1: How many do you currently have in inventory (${prodname1})"
cap lab var Q6u1_t1 "Number"
cap lab var Q6u2_t1 "Unit"
cap lab var Q6u2_calc_t1a "unit label"
cap lab var Q6u2_t1_oth "Please specify unit"
cap lab var Q6u3_t1 "How would you compare your 12 months (Sept-Aug 2017) productivity with the year before (Sept-Aug 2016) for (${prodname1})?"
cap lab var Q6u4_t1 "Do you sell ANY for cash (${prodname1})?"
cap lab var Q6u5_t1 "How many ${Q6u2_calc_t1a} did you sell in the past 30 DAYS (${prodname1})?"
cap lab var Q6u8_t1 "For what price did you sell each product (${prodname1})?"
cap lab var Q6u9_t1 "What is the value of the goods you receive in exchange for this product (${prodname1})?"
cap lab var Q6u10_t1 "Where are these products (${prodname1}) sold first by your business/household?"
cap lab var Q6u10_t1_other "Other (Please Spicify)"
cap lab var Q6u11_t1 "Who transports these products (${prodname1}) to the point of sale?"
cap lab var Q6u12_t1 "Do you pay a fee for this transport of (${prodname1})?"
cap lab var prod2 "Product details"
cap lab var prodid2 "product id"
cap lab var prodname2_oth "You selected "Other" product from your (Raising livestock/Poultry/Bees) activities. Please specify."
cap lab var prodname2_reg "product label if selected from list"
cap lab var prodname2 "product label"
cap lab var inv2 "inventory"
cap lab var inventorynote2 "Q6u1: How many do you currently have in inventory (${prodname2})"
cap lab var Q6u1_t2 "Number"
cap lab var Q6u2_t2 "Unit"
cap lab var Q6u2_calc_t2 "unit label"
cap lab var Q6u3_t2 "How would you compare your 12 months (Sept-Aug 2017) productivity with the year before (Sept-Aug 2016) for (${prodname2})?"
cap lab var Q6u4_t2 "Do you sell ANY for cash (${prodname2})?"
cap lab var Q6u5_t2 "How many ${Q6u2_calc_t2} did you sell in the past 30 DAYS (${prodname2})?"
cap lab var Q6u8_t2 "For what price did you sell each product (${prodname2})?"
cap lab var Q6u9_t2 "What is the value of the goods you receive in exchange for this product (${prodname2})?"
cap lab var Q6u10_t2 "Where are these products (${prodname2}) sold first by your business/household?"
cap lab var Q6u10_t2_other "Other (Please Spicify)"
cap lab var Q6u11_t2 "Who transports these products (${prodname2}) to the point of sale?"
cap lab var Q6u12_t2 "Do you pay a fee for this transport of (${prodname2})?"
cap lab var prod3 "Product details"
cap lab var prodid3 "product id"
cap lab var prodname3_oth "You selected "Other" product from your (Wholesale trade/sales) activities. Please specify."
cap lab var prodname3_reg "product label if selected from list"
cap lab var prodname3 "product label"
cap lab var inv3 "inventory"
cap lab var inventorynote3 "Q6u1: How many do you currently have in inventory (${prodname3})"
cap lab var Q6u1_t3 "Number"
cap lab var Q6u2_t3 "Unit"
cap lab var Q6u2_t3_other "Other (Please Spicify)"
cap lab var Q6u2_calc_t3 "unit label"
cap lab var Q6u3_t3 "How would you compare your 12 months (Sept-Aug 2017) productivity with the year before (Sept-Aug 2016) for (${prodname3})?"
cap lab var Q6u4_t3 "Do you sell ANY for cash (${prodname3})?"
cap lab var Q6u5_t3 "How many ${Q6u2_calc_t3} did you sell in the past 30 DAYS (${prodname3})?"
cap lab var Q6u8_t3 "For what price did you sell each product (${prodname3})?"
cap lab var Q6u9_t3 "What is the value of the goods you receive in exchange for this product (${prodname3})?"
cap lab var Q6u10_t3 "Where are these products (${prodname3}) sold first by your business/household?"
cap lab var Q6u2_t4_other "Other (Please Spicify)"
cap lab var Q6u11_t3 "Who transports these products (${prodname3}) to the point of sale?"
cap lab var Q6u12_t3 "Do you pay a fee for this transport of (${prodname3})?"
cap lab var prod4 "Product details"
cap lab var prodid4 "product id"
cap lab var prodname4_oth "You selected "Other" product from your (Retail trade/sales) activities. Please specify."
cap lab var prodname4_reg "product label if selected from list"
cap lab var prodname4 "product label"
cap lab var inv4 "inventory"
cap lab var inventorynote4 "Q6u1: How many do you currently have in inventory (${prodname4})"
cap lab var Q6u1_t4 "Number"
cap lab var Q6u1_t4_other "Other (Please Spicify)"
cap lab var Q6u2_t4 "Unit"
cap lab var Q6u2_calc_t4 "unit label"
cap lab var Q6u3_t4 "How would you compare your 12 months (Sept-Aug 2017) productivity with the year before (Sept-Aug 2016) for (${prodname4})?"
cap lab var Q6u4_t4 "Do you sell ANY for cash (${prodname4})?"
cap lab var Q6u5_t4 "How many ${Q6u2_calc_t4} did you sell in the past 30 DAYS (${prodname4})?"
cap lab var Q6u8_t4 "For what price did you sell each product (${prodname4})?"
cap lab var Q6u9_t4 "What is the value of the goods you receive in exchange for this product (${prodname4})?"
cap lab var Q6u10_t4 "Where are these products (${prodname4}) sold first by your business/household?"
cap lab var Q6u11_t4 "Who transports these products (${prodname4}) to the point of sale?"
cap lab var Q6u12_t4 "Do you pay a fee for this transport of (${prodname4})?"
cap lab var prod5 "Product details"
cap lab var prodid5 "product id"
cap lab var prodname5_oth "You selected "Other" product from your (Food production/processing) activities. Please specify."
cap lab var prodname5_reg "product label if selected from list"
cap lab var prodname5 "product label"
cap lab var inv5 "inventory"
cap lab var inventorynote5 "Q6u1: How many do you currently have in inventory (${prodname5})"
cap lab var Q6u1_t5 "Number"
cap lab var Q6u2_t5 "Unit"
cap lab var Q6u2_t5_other "Other (Please Spicify)"
cap lab var Q6u2_calc_t5 "unit label"
cap lab var Q6u3_t5 "How would you compare your 12 months (Sept-Aug 2017) productivity with the year before (Sept-Aug 2016) for (${prodname5})?"
cap lab var Q6u4_t5 "Do you sell ANY for cash (${prodname5})?"
cap lab var Q6u5_t5 "How many ${Q6u2_calc_t5} did you sell in the past 30 DAYS (${prodname5})?"
cap lab var Q6u8_t5 "For what price did you sell each product (${prodname5})?"
cap lab var Q6u9_t5 "What is the value of the goods you receive in exchange for this product (${prodname5})?"
cap lab var Q6u10_t5 "Where are these products (${prodname5}) sold first by your business/household?"
cap lab var Q6u10_t5_other "Other (Please Spicify)"
cap lab var Q6u11_t5 "Who transports these products (${prodname5}) to the point of sale?"
cap lab var Q6u12_t5 "Do you pay a fee for this transport of (${prodname5})?"
cap lab var prod6 "Product details"
cap lab var prodid6 "product id"
cap lab var prodname6_oth "You selected "Other" product from your (Manufacturing) activities. Please specify."
cap lab var prodname6_reg "product label if selected from list"
cap lab var prodname6 "product label"
cap lab var inv6 "inventory"
cap lab var inventorynote6 "Q6u1: How many do you currently have in inventory (${prodname6})"
cap lab var Q6u1_t6 "Number"
cap lab var Q6u2_t6 "Unit"
cap lab var Q6u2_t6_other "Other (Please Spicify)"
cap lab var Q6u2_calc_t6 "unit label"
cap lab var Q6u3_t6 "How would you compare your 12 months (Sept-Aug 2017) productivity with the year before (Sept-Aug 2016) for (${prodname6})?"
cap lab var Q6u4_t6 "Do you sell ANY for cash (${prodname6})?"
cap lab var Q6u5_t6 "How many ${Q6u2_calc_t6} did you sell in the past 30 DAYS (${prodname6})?"
cap lab var Q6u8_t6 "For what price did you sell each product (${prodname6})?"
cap lab var Q6u9_t6 "What is the value of the goods you receive in exchange for this product (${prodname6})?"
cap lab var Q6u10_t6 "Where are these products (${prodname6}) sold first by your business/household?"
cap lab var Q6u10_t6_other "Other (Please Spicify)"
cap lab var Q6u11_t6 "Who transports these products (${prodname6}) to the point of sale?"
cap lab var Q6u12_t6 "Do you pay a fee for this transport of (${prodname6})?"
cap lab var prod7 "Product details"
cap lab var prodid7 "product id"
cap lab var prodname7_oth "You selected "Other" product from your (Non-agriculture business) activities. Please specify."
cap lab var prodname7_reg "product label if selected from list"
cap lab var prodname7 "product label"
cap lab var inv7 "inventory"
cap lab var inventorynote7 "Q6u1: How many do you currently have in inventory (${prodname7})"
cap lab var Q6u1_t7 "Number"
cap lab var Q6u2_t7 "Unit"
cap lab var Q6u2_t7_other "Other (Please Spicify)"
cap lab var Q6u2_calc_t7 "unit label"
cap lab var Q6u3_t7 "How would you compare your 12 months (Sept-Aug 2017) productivity with the year before (Sept-Aug 2016) for (${prodname7})?"
cap lab var Q6u4_t7 "Do you sell ANY for cash (${prodname7})?"
cap lab var Q6u5_t7 "How many ${Q6u2_calc_t7} did you sell in the past 30 DAYS (${prodname7})?"
cap lab var Q6u8_t7 "For what price did you sell each product (${prodname7})?"
cap lab var Q6u9_t7 "What is the value of the goods you receive in exchange for this product (${prodname7})?"
cap lab var Q6u10_t7 "Where are these products (${prodname7}) sold first by your business/household?"
cap lab var Q6u10_t7_other "Other (Please Spicify)"
cap lab var Q6u11_t7 "Who transports these products (${prodname7}) to the point of sale?"
cap lab var Q6u12_t7 "Do you pay a fee for this transport of (${prodname7})?"
cap lab var prod8 "Product details"
cap lab var prodid8 "product id"
cap lab var prodname8_oth "You selected "Other" product from your (Transportation and Communication) activities. Please specify."
cap lab var prodname8_reg "product label if selected from list"
cap lab var prodname8 "product label"
cap lab var inv8 "inventory"
cap lab var inventorynote8 "Q6u1: How many do you currently have in inventory (${prodname8})"
cap lab var Q6u1_t8 "Number"
cap lab var Q6u2_t8 "Unit"
cap lab var Q6u2_t8_other "Other (Please Spicify)"
cap lab var Q6u2_calc_t8 "unit label"
cap lab var Q6u3_t8 "How would you compare your 12 months (Sept-Aug 2017) productivity with the year before (Sept-Aug 2016) for (${prodname8})?"
cap lab var Q6u4_t8 "Do you sell ANY for cash (${prodname8})?"
cap lab var Q6u5_t8 "How many ${Q6u2_calc_t8} did you sell in the past 30 DAYS (${prodname8})?"
cap lab var Q6u8_t8 "For what price did you sell each product (${prodname8})?"
cap lab var Q6u9_t8 "What is the value of the goods you receive in exchange for this product (${prodname8})?"
cap lab var Q6u10_t8 "Where are these products (${prodname8}) sold first by your business/household?"
cap lab var Q6u10_t8_other "Other (Please Spicify)"
cap lab var Q6u11_t8 "Who transports these products (${prodname8}) to the point of sale?"
cap lab var Q6u12_t8 "Do you pay a fee for this transport of (${prodname8})?"
cap lab var Q7a1 "Do you have a tazkira?"
cap lab var Q7a2 "We would like to confirm if you have it and are using it directly. Can I see your tazkira?"
cap lab var Q7b1 "Has any member of your household participated in any food-for-work or food aid programmes during the past 12 months?"
cap lab var Q7b2 "Please estimate the value of the total amount received from this program over the past 12 months"
cap lab var Q7c1 "Has any member of your household participated in any cash-for-work or income generating programmes by a governmental or non-governmental organization during the past 12 months?"
cap lab var Q7c2 "Please estimate the value of the total amount received from this program over the past 12 months"
cap lab var Q7d1 "Has any member of your household participated in any cash transfer programmes by a governmental or non-governmental organization during the past 12 months?"
cap lab var Q7d2 "Please estimate the value of the total amount received from this program over the past 12 months"
cap lab var Q7e "Has any member of your household received agriculture extension services in the past 12 months?"
cap lab var Q7f1 "Have you received any training in the past 12 months?"
cap lab var Q7f2 "What kind of training was it?"
cap lab var Q7g1 "Are you part of a community based savings group (CBSG)?"
cap lab var Q7g_error "Please verify last response"
cap lab var Q7g2 "When did you join your CBSG?"
cap lab var Q7h1 "What is your position or role in your CBSG?"
cap lab var Q7h2 "Have you ever had an officer position?"
cap lab var Q7i "How often are meetings held?"
cap lab var Q7j1 "How many meetings have been held by your CBSG in the past 3 months?"
cap lab var Q7j2 "How many CBSG meetings have you attended in the past 3 months?"
cap lab var Q7j3 "Calcuation"
cap lab var Q7j4 "What makes it difficult to attend CBSG meetings on a regular basis?"
cap lab var Q7j4_other "If other, please specify"
cap lab var Q7j5 "How long does it take you to travel to CBSG meetings from your home by walking (in minutes)?"
cap lab var Q7k1 "How much money do you have saved with your CBSG?"
cap lab var Q7k2 "Enumerator do not read: how confident is individual in response"
cap lab var Q7l "How much money do you usually save per month with your CBSG, in general"
cap lab var Q7m1 "Have you taken any loans from your CBSG since formation?"
cap lab var Q7m2 "What have you used this money for?"
cap lab var Q7m3 "If selected 15, What type of product did you invest in?"
cap lab var Q7m3_other "Other Specify"
cap lab var Q7m4 "How much do you currently owe to your CBSG?"
cap lab var Q7m_error "You stated that you have never taken a CBSG loan, but you still owe funds. Please go back and correct one response."
cap lab var Q7n "How much money does your CBSG have saved as a whole?"
cap lab var Q7o "What interest rate do members have to pay if they take a loan from the CBSG?"
cap lab var note_intro_mod8 "Script: Now I would like to ask you about financial activities, such as savings and credit. In the following questions, we are asking about your HOUSEHOLD."
cap lab var Q8a "Do you have any cash funds that you have saved or set aside?"
cap lab var Q8b "Do you, either by yourself or together with any other member of your household, currently have an account at any of the following places: a bank, a microfinance organization, or any other type of formal financial institution?"
cap lab var Q8c1 "Where is the money saved?"
cap lab var Q8c1_other "If Other, Please specify"
cap lab var Q8c2 "In total how much are your cash savings now, including funds you have saved at home, at a bank, with a savings group, or with another individual or group?"
cap lab var Q8c3 "In the past 12 months, has money been DEPOSITED into this/these personal account(s)? This includes cash or electronic deposits, or any time money is put into your account(s) by yourself, an employer, or another person or institution."
cap lab var Q8c4 "What are you saving for? Please list every reason"
cap lab var Q8c4_other "Other Specify"
cap lab var Q8c5 "Do individuals outside of your family, but within your household, have access to your savings at any time?"
cap lab var Q8d "Why don't you have a formal account?"
cap lab var Q8e "Do you have any outstanding financial loans/ debts at present individually or with someone else?"
cap lab var Q8e1 "What interest rate do you pay on your largest loan?"
cap lab var Q8e2 "What is the value of the total outstanding financial debt for this household at present? (amount owed by the household to others)?"
cap lab var Q8e3 "To whom do you owe money?"
cap lab var Q8e3_other "Other Specify"
cap lab var Q8e4 "What has the money been used for?"
cap lab var Q8e4_other "Other Specify"
cap lab var Q8e5 "Why do you and other members of your household not have any outstanding loans?"
cap lab var Q8f "Are you responsible for the debt of other household members outside of your family?"
cap lab var Q8g "Imagine you have an emergency and you need to pay AFG 2060. From where do you think you would be able to successfully obtain a loan for this amount?"
cap lab var Q8g_other "Other Specify"
cap lab var note_financial "I will now ask you several questions related to your financial practices"
cap lab var Q9a1 "Do you keep track of the money you spend and the money you get for your personal finances (household savings, personal expenditures, etc.)?"
cap lab var Q9a2 "How do you keep track of your personal finances?"
cap lab var Q9b1 "Do you keep track of the money you spend and the money you get for your business activities?"
cap lab var Q9b2 "How do you keep track of your business budget?"
cap lab var Q9b3 "Do you track your personal finances (household savings, personal expenditures, etc.) and your business finances separately?"
cap lab var bus "Business-related hard skills"
cap lab var note_business "I will now ask you several questions related to your business practices"
cap lab var Q9c1 "Over the past 3 months, have you kept track of Purchases of inputs/materials for production"
cap lab var Q9c2 "Over the past 3 months, have you kept track of  Purchases of business assets"
cap lab var Q9c3 "Over the past 3 months, have you kept track of  Payments made to employees"
cap lab var Q9c4 "Over the past 3 months, have you kept track of  Other administrative costs to the business (rent, fees, taxes, electricity,etc.)"
cap lab var Q9c5 "Over the past 3 months, have you kept track of  Sales of products"
cap lab var Q9c6 "Over the past 3 months, have you kept track of  Total products you have in stock"
cap lab var Q9c7 "Over the past 3 months, have you kept track of  Prices of equivalent products from different sources"
cap lab var Q9c8 "Over the past 3 months, have you kept track of  Loan payments due or debts accrued to suppliers"
cap lab var Q9d "Do know the cost to the business of each main product you sell? This includes any costs that are required for creating the product."
cap lab var Q9e "Do you ever calculate profits made by your business?"
cap lab var Q9f1 "In the past 12 months, have you cut costs or expenditure"
cap lab var Q9f2 "In the past 12 months, have you worked with with at least one new supplier"
cap lab var Q9f3 "In the past 12 months, have you purchased higher quality inputs"
cap lab var Q9f4 "In the past 12 months, have you tried to negotiate with any of your suppliers for a lower price of particular product"
cap lab var Q9f5 "In the past 12 months, have you  compared the prices or quality offered by alternate suppliers to the prices offered by current suppliers"
cap lab var Q9f6 "In the past 12 months, have you got a loan from a formal financial institution for your business"
cap lab var Q9f7 "In the past 12 months, have you cooperated with current competitors"
cap lab var Q9f8 "In the past 12 months, have you tried to learn the selling price of competitors"
cap lab var Q9f9 "In the past 12 months, have you taken steps to attract more/higher paying customers"
cap lab var Q9f10 "In the past 12 months, have you had a change in the number of buyers/customers for your products? In which direction?"
cap lab var Q9g1 "In the past 12 months, how often do you discuss where to sell your product?"
cap lab var Q9g2 "In the past 12 months, with whom do you discuss where to sell your product the most often?"
cap lab var Q9g2_other "Other Specify"
cap lab var Q9h1 "In the past 12 months, How often do you discuss improving the quality of your product?"
cap lab var Q9h2 "In the past 12 months, With whom do you discuss improving the quality of your product the most often?"
cap lab var Q9h2_other "Other Specify"
cap lab var Q9i1 "In the past 12 months, How often do you discuss what products to sell?"
cap lab var Q9i2 "In the past 12 months, With whom do you discuss what products to sell the most often?"
cap lab var Q9i2_other "Other Specify"
cap lab var Q9j1 "In the past 12 months, How often do you discuss finding suppliers/inputs?"
cap lab var Q9j2 "In the past 12 months, With whom do you discuss finding suppliers/inputs most often?"
cap lab var Q9k "If you wanted to improve profits, what would be the best ways to do it"
cap lab var Q9k_other "Please specify"
cap lab var note_puzzles "I will now ask you a few questions and puzzles, to learn more about the way you think"
cap lab var Q9l "How should one calculate profits"
cap lab var Q9l_other "Other Specify"
cap lab var Q9m "Suppose you have deposited 5000 Afs in the bank for an interest of 10 percent per year. If you withdraw all the money after 1 year, how much will you get?"
cap lab var Q9n "Please tell me 3 things that you think are important when taking out a loan from any source."
cap lab var Q9n_other "Other Specify"
cap lab var Q9o "Please name some services you can get at a bank."
cap lab var Q9o_other "Other Specify"
cap lab var Q9p "I will now read different sequences of digits. Every time I finish a sequence I would like you to repeat as many digits as you can in the order that I read them.  That means Beginning from the first and ending with the last.  For instance, when I read 1, 5, 2, after I am done reading, you respond 1, 5, 2. Every time you correctly recall a sequence, the next sequence will be one digit longer. Please listen carefully. 637,4539,16582,649735,3145782,74529638,794831265,8491285637,"
cap lab var Q9q "Now, I will read sequences of numbers and every time I finish a sequence I would like you to repeat as many digits or numbers as you can recall in the reverse order. That means Beginning from the last and ending with the first. So, when I read 1, 5, 2, after I am done reading, you respond 2, 5, 1. Once again, every time you correctly recall a sequence, the next sequence will be one digit longer. Please listen carefully  637,4539,16582,649735,3145782,74529638,794831265,8491285637"
cap lab var Q10a "In the last 30 days, that is, the last one month, how many days did you attend any kind of group meeting with members of your community?"
cap lab var Q10a1 "During those meetings, how often did you speak such that everyone at the meeting could hear you?"
cap lab var Q10b "Did you attend any CDC/village meetings in the last 12 MONTHS?"
cap lab var Q10c "Are you a leader in your community, school, mosque, or in any groups?"
cap lab var Q10cbsg2 "How frequently do you leave your village?"
cap lab var Q10cbsg3 "How frequently do you travel to your local market?"
cap lab var Q10cbsg4 "How far away was this market (in km)?"
cap lab var Q10cbsg5 "Are you usually accompanied by any other adults?"
cap lab var Q10cbsg6 "Who usually accompanies you?"
cap lab var Q10cbsg9 "In a typical week, how many days did you meet friends who reside outside of your neighborhood?"
cap lab var social "social"
cap lab var social_heading "How often do you feel the following: Never, Rarely, Sometimes, Usually/Always"
cap lab var Q10cbsg10 "I have someone who understands my problems"
cap lab var Q10cbsg11 "I have someone who will listen to me when I need to talk"
cap lab var Q10cbsg12 "I feel there are people I can talk to if I am upset"
cap lab var Q10cbsg14 "I have someone I trust to talk with about my problems"
cap lab var Q10cbsg15 "I have someone I trust to talk with about my feelings"
cap lab var Q10cbsg16 "I can get helpful advice from others when dealing with a problem"
cap lab var Q10cbsg18 "I feel alone and apart from others"
cap lab var howtrue "how true"
cap lab var Q10d_note "Is each statement Never True, Not very true, Somewhat true, or Always true:"
cap lab var Q10d "My actions on what types of work I do are determined by the situation. I don’t really have an option."
cap lab var Q10e "My actions in what types of work I do are partly because I will get in trouble with someone if I act differently."
cap lab var Q10f "Regarding the types of work I do, I do what I do so others don’t think poorly of me."
cap lab var Q10g "Regarding the types of work I do, I do what I do because I personally think it is the right thing to do."
cap lab var Q10h1 "How much would YOUR opinion be considered in the final decision if your household needs to decide on the following things:"
cap lab var Q10h2 "Buying groceries"
cap lab var Q10h3 "Buying expensive items (i.e. mobile phone, farm equipment)"
cap lab var Q10h4 "Buying or selling land or property"
cap lab var Q10h5 "Whether your daughter should attend school"
cap lab var Q10h6 "Whether your son should attend school"
cap lab var Q10h7 "Marriage of children"
cap lab var Q10h8 "How many children to have"
cap lab var Q10h9 "You wanted to pursue a job outside the home"
cap lab var Q10i1 "How much input do you have in making decisions about INCOME HE/SHE EARNS?"
cap lab var Q10i3 "To what extent do you feel you can make your own personal decisions regarding  INCOME HE/SHE EARNS if you want(ed) to?"
cap lab var Q10j1 "How much input do you have in making decisions about HOW HOUSEHOLD INCOME IS SPENT?"
cap lab var Q10j3 "To what extent do you feel you can make your own personal decisions regarding  HOW HOUSEHOLD INCOME IS SPENT if you want(ed) to?"
cap lab var Q10k1 "How much input do you have in making decisions about WHICH BUSINESS OPPORTUNITIES TO PURSUE?"
cap lab var Q10k3 "To what extent do you feel you can make your own personal decisions on WHICH BUSINESS OPPORTUNITIES TO PURSUE if you want(ed) to?"
cap lab var Q10l1 "How much input do you have in making decisions about PURCHASING MATERIALS FOR YOUR BUSINESS?"
cap lab var Q10l3 "To what extent do you feel you can make your own personal decisions on PURCHASING MATERIALS FOR YOUR BUSINESS if you want(ed) to?"
cap lab var howconf "how confident"
cap lab var Q10cbsg0 "Business ability"
cap lab var Q10cbsg33 "Estimate accurately the costs of producing products and services"
cap lab var Q10cbsg34 "Manage an employee who is not a member of your family"
cap lab var Q10cbsg35 "Resolve a difficult dispute with a customer or supplier"
cap lab var note_agree1 "I will now ask you series of questions. Please let me know your level of agreement, where the options are: Strongly Disagree, Disagree, Agree, or Strongly Agree"
cap lab var Q10cbsg36 "I feel that I have a number of good qualities"
cap lab var Q10cbsg37 "At times I think I am no good at all"
cap lab var Q10cbsg38 "I am able to do things as well as most other people"
cap lab var Q10cbsg39 "I feel I do not have much to be proud of"
cap lab var Q10cbsg40 "I certainly feel useless at times"
cap lab var Q10cbsg41 "I feel that I'm a person of worth, at least on an equal plane with others"
cap lab var Q10cbsg42 "I wish I could have more respect for myself"
cap lab var note_agree2 "I will now ask you series of questions. Please let me know your level of agreement, where the options are: Strongly Disagree, Disagree, Agree, or Strongly Agree"
cap lab var Q10cbsg43 "In uncertain times I usually expect the best"
cap lab var Q10cbsg44 "If something can go wrong for me, it will"
cap lab var Q10cbsg45 "I'm always optimistic about my future"
cap lab var Q10cbsg46 "I hardly ever expect things to go my way"
cap lab var Q10cbsg47 "I rarely count on good things happening to me"
cap lab var Q10cbsg48 "Overall I expect more good things to happen to me than bad"
cap lab var Q10cbsg49 "I believe that my success depends more on ability than luck"
cap lab var Q10cbsg50 "Our intelligence is a characteristic we cannot change much"
cap lab var Q10cbsg51 "We are intelligent up to a certain point and we cannot do much to change that"
cap lab var Q10cbsg52 "We may learn new things but we cannot change our basic intelligence"
cap lab var note_agree3 "I will now ask you series of questions. Please let me know your level of agreement, where the options are: Strongly Disagree, Disagree, Agree, or Strongly Agree"
cap lab var Q10cbsg65 "To a great extent my life is controlled by accidental happenings"
cap lab var Q10cbsg66 "I feel like what happens in my life is mostly determined by powerful people"
cap lab var Q10cbsg67 "When I make plans, I am almost certain to make them work"
cap lab var Q10cbsg69 "When I get what I want, it’s usually because I am lucky"
cap lab var Q10cbsg70 "Although I might have good ability, I will not be given leadership responsibility without appealing to those in positions of power"
cap lab var Q10cbsg71 "I have often found that what is going to happen will happen"
cap lab var Q10cbsg73 "People like myself have very little chance of protecting our personal interests when they conflict with those of strong pressure groups"
cap lab var Q10cbsg74 "It’s not always wise for me to plan too far ahead because many things turn out to be a matter of good or bad fortune"
cap lab var Q10cbsg76 "The work you do is important to you"
cap lab var Q10cbsg77 "If you disregard the help you receive from other household members, how do you and your spouse/partner divide the following tasks? PREPARING FOOD"
cap lab var Q10cbsg78 "If you disregard the help you receive from other household members, how do you and your spouse/partner divide the following tasks? CLEANING THE HOUSE AND WASHING THE CLOTHES"
cap lab var Q10cbsg79 "If you disregard the help you receive from other household members, how do you and your spouse/partner divide the following tasks? TAKING CARE OF CHILDREN"
cap lab var Q10cbsg80 "Taking all things together, how happy would you say you are?"
cap lab var Q10m1 "How much do you agree or disagree with the following statement: The important decisions in the family should be made only by the men of the family."
cap lab var Q10m2 "How much do you agree or disagree with the following statement: If the wife is working outside the home, then the husband should help her with the household chores."
cap lab var Q10m3 "How much do you agree or disagree with the following statement: A married woman should be allowed to work outside the home if she wants to."
cap lab var Q10m4 "How much do you agree or disagree with the following statement: A wife should tolerate being beaten by her husband in order to keep the family together."
cap lab var Q10m5 "How much do you agree or disagree with the following statement: It is better to send a son to school than it is to send a daughter."
cap lab var Q10m6 "How much do you agree or disagree with the following statement: The wife has a right to express her opinion even if she disagrees with what her husband is saying"
cap lab var Q10cbsg88 "On a scale from 1 to 10, how often have you felt unsafe walking in your village during the DAY in the last 12 months? Where 1 is very rarely and 10 is very often."
cap lab var Q10cbsg89 "On a scale from 1 to 10, how often have you felt unsafe walking in your village at NIGHT in the last 12 months? Where 1 is very rarely and 10 is very often."
cap lab var text13 "End of the survey for the interviewee. Please thank them for their time."
cap lab var gps "Record GPS"
cap lab var Q99a "Interview language"
cap lab var Q99a_other "Other (Please Spicify)"
cap lab var Q99b "Interview status"
cap lab var Q99c "On a scale of 1 (poorest) to 10 (wealthiest), how wealthy do you think the respondent's household is in comparison with other households in the village/community?"
cap lab var Q99d "How was the degree of co-operation of the respondent?"
cap lab var Q99e "During the interview of the respondent, was anyone else in listening?"
cap lab var Q99e1 "Do you think the presence of another person influenced the answers of the respondent?"
cap lab var Q99f "If no GPS Coordinates can be collected, mark down the address of the household, or a description and landmarks for relocating."
cap lab var Q99g "Please record any general notes about the interview and any special information that will be helpful for supervisors, office editors, and data analysis."
