cap lab val cbsg_started yesno
cap lab val resp_ver yesno
cap lab val Q1k yesno
cap lab val Q1k_whynot whynot_mkp
cap lab val Q1m3_0 yesno
cap lab val Q1m4_0 yesno
cap lab val Q1m5_0 yesno
cap lab val Q2c res_status
cap lab val Q2g relationship
cap lab val Q2h female
cap lab val Q2i marital
cap lab val Q2j yes_no
cap lab val Q2k1 yes_no
cap lab val Q2k2 migration

forv i = 1/27 {
	cap lab val Q2l_`i' literacy
}

cap lab val Q2m curr_attend
cap lab val Q2n1 education
cap lab val Q2r yes_no
cap lab val Q2s yes_no
cap lab val Q2t reasonnowork
cap lab val Q2u activities
cap lab val Q2w1 of_seven
cap lab val Q2w3 yes_no
cap lab val Q2w4 payment
cap lab val Q2w5 employer
cap lab val Q3a yesno
cap lab val Q3a_name1 yesno
cap lab val Q3a_name2 yesno
cap lab val Q3a_name3 yesno
cap lab val Q3a_name4 yesno
cap lab val Q3a_name5 yesno
cap lab val Q3a_name6 yesno
cap lab val Q3a_name7 yesno
cap lab val Q3a_name8 yesno
cap lab val Q3a_name9 yesno
cap lab val Q3a_name10 yesno
cap lab val Q3a_name11 yesno
cap lab val Q3a_name12 yesno
cap lab val Q3a_name13 yesno
cap lab val Q3a_name14 yesno
cap lab val Q3a_name15 yesno
cap lab val Q3a_name16 yesno
cap lab val Q3a_name17 yesno
cap lab val Q3a_name18 yesno
cap lab val Q3a_name19 yesno
cap lab val Q3a_name20 yesno
cap lab val Q3b hoh
cap lab val Q3c yesno
cap lab val Q3c_name1 yesno
cap lab val Q3c_name2 yesno
cap lab val Q3c_name3 yesno
cap lab val Q3c_name4 yesno
cap lab val Q3c_name5 yesno
cap lab val Q3c_name6 yesno
cap lab val Q3c_name7 yesno
cap lab val Q3c_name8 yesno
cap lab val Q3c_name9 yesno
cap lab val Q3c_name10 yesno
cap lab val Q3c_name11 yesno
cap lab val Q3c_name12 yesno
cap lab val Q3c_name13 yesno
cap lab val Q3c_name14 yesno
cap lab val Q3c_name15 yesno
cap lab val Q3c_name16 yesno
cap lab val Q3c_name17 yesno
cap lab val Q3c_name18 yesno
cap lab val Q3c_name19 yesno
cap lab val Q3c_name20 yesno
cap lab val marstatus marital
cap lab val Q3d yesno
cap lab val Q3d_na yesno
cap lab val Q3d_name1 yesno
cap lab val Q3d_name2 yesno
cap lab val Q3d_name3 yesno
cap lab val Q3d_name4 yesno
cap lab val Q3d_name5 yesno
cap lab val Q3d_name6 yesno
cap lab val Q3d_name7 yesno
cap lab val Q3d_name8 yesno
cap lab val Q3d_name9 yesno
cap lab val Q3d_name10 yesno
cap lab val Q3d_name11 yesno
cap lab val Q3d_name12 yesno
cap lab val Q3d_name13 yesno
cap lab val Q3d_name14 yesno
cap lab val Q3d_name15 yesno
cap lab val Q3d_name16 yesno
cap lab val Q3d_name17 yesno
cap lab val Q3d_name18 yesno
cap lab val Q3d_name19 yesno
cap lab val Q3d_name20 yesno
cap lab val parstatus yesno
cap lab val Q3e yesno
cap lab val Q3e_na yesno
cap lab val Q3e_name1 yesno
cap lab val Q3e_name2 yesno
cap lab val Q3e_name3 yesno
cap lab val Q3e_name4 yesno
cap lab val Q3e_name5 yesno
cap lab val Q3e_name6 yesno
cap lab val Q3e_name7 yesno
cap lab val Q3e_name8 yesno
cap lab val Q3e_name9 yesno
cap lab val Q3e_name10 yesno
cap lab val Q3e_name11 yesno
cap lab val Q3e_name12 yesno
cap lab val Q3e_name13 yesno
cap lab val Q3e_name14 yesno
cap lab val Q3e_name15 yesno
cap lab val Q3e_name16 yesno
cap lab val Q3e_name17 yesno
cap lab val Q3e_name18 yesno
cap lab val Q3e_name19 yesno
cap lab val Q3e_name20 yesno
cap lab val Q3f yesno
cap lab val Q3f_na yesno
cap lab val Q3f_name1 yesno
cap lab val Q3f_name2 yesno
cap lab val Q3f_name3 yesno
cap lab val Q3f_name4 yesno
cap lab val Q3f_name5 yesno
cap lab val Q3f_name6 yesno
cap lab val Q3f_name7 yesno
cap lab val Q3f_name8 yesno
cap lab val Q3f_name9 yesno
cap lab val Q3f_name10 yesno
cap lab val Q3f_name11 yesno
cap lab val Q3f_name12 yesno
cap lab val Q3f_name13 yesno
cap lab val Q3f_name14 yesno
cap lab val Q3f_name15 yesno
cap lab val Q3f_name16 yesno
cap lab val Q3f_name17 yesno
cap lab val Q3f_name18 yesno
cap lab val Q3f_name19 yesno
cap lab val Q3f_name20 yesno
cap lab val Q3g finalsay
cap lab val Q3h finalsay
cap lab val Q3i finalsay
cap lab val Q4a possible
cap lab val Q4c yes_no
cap lab val Q4d1 yes_no
cap lab val Q4d_note freq
cap lab val Q4d2 freq
cap lab val Q4d3 freq
cap lab val Q4d4 freq
cap lab val Q4d5 freq
cap lab val Q4e0 of_seven
cap lab val Q4e1 of_seven
cap lab val Q4e2 of_seven
cap lab val Q4e3 of_seven
cap lab val Q4e4 of_seven
cap lab val Q4e5 of_seven
cap lab val Q4e6 of_seven
cap lab val Q4e7 of_seven
cap lab val Q4e8 of_seven
cap lab val Q4e9 of_seven
cap lab val Q5a dwelltype
cap lab val Q5c occupancy
cap lab val Q5f1 yes_no
cap lab val Q5f2 yes_no
cap lab val Q5f3 yes_no
cap lab val Q5f4 yes_no
cap lab val Q5g heating
cap lab val Q5h toilet
cap lab val Q5i yes_no
cap lab val Q5j water
cap lab val Q5l phone
cap lab val Q5m1 yes_no
cap lab val Q5m9 yes_no
cap lab val Q5assets asset
cap lab val Q10a1 freq_sel_nih2
cap lab val Q10b yes_no
cap lab val Q10c yes_no
cap lab val Q10d_note true_dec
cap lab val Q10d true_dec
cap lab val Q10e true_dec
cap lab val Q10f true_dec
cap lab val Q10g true_dec
cap lab val Q10h1 decision
cap lab val Q10h2 decision
cap lab val Q10h3 decision
cap lab val Q10h4 decision
cap lab val Q10h5 decision
cap lab val Q10h6 decision
cap lab val Q10h7 decision
cap lab val Q10h8 decision
cap lab val Q10h9 decision
cap lab val Q10i1 dec_input
cap lab val Q10i2 dec_who_mkp
cap lab val Q10i3 extent
cap lab val Q10j1 dec_input
cap lab val Q10j2 dec_who_mkp
cap lab val Q10j3 extent
cap lab val Q10k1 dec_input
cap lab val Q10k2 dec_who_mkp
cap lab val Q10k3 extent
cap lab val Q10l1 dec_input
cap lab val Q10l2 dec_who_mkp
cap lab val Q10l3 extent
cap lab val Q10m1 agree
cap lab val Q10m2 agree
cap lab val Q10m3 agree
cap lab val Q10m4 agree
cap lab val Q10m5 agree
cap lab val Q10m6 agree
cap lab val Q99a language
cap lab val Q99b status
cap lab val Q99d cooperation
cap lab val Q99e yesno
cap lab val Q99e1 yesno
