cap lab var hhid "Enter hhid of the household you plan to survey"
cap lab var sfprovince "Pre-filled: Province"
cap lab var sfdistrict "Pre-filled: District"
cap lab var sfcdc "Pre-filled: CDC"
cap lab var sfvillage "Pre-filled: Village"
cap lab var sfcbsg_resp "Pre-filled: Name of CBSG member/respondent"
cap lab var sfcbsg "Pre-filled: Name of CBSG"
cap lab var sfnumber1 "Pre-filled: Mobile Number"
cap lab var sfnumber2 "Pre-filled: Alt Mobile"
cap lab var sfnumber3 "Pre-filled: Alt Mobile 2"
cap lab var note_hhid "HHID: ${hhid}"
cap lab var note_sfcbsg_resp "CBSG participant: ${sfcbsg_resp}"
cap lab var note_sfprovince "Province: ${sfprovince}"
cap lab var note_sfdistrict "District: ${sfdistrict}"
cap lab var note_sfcdc "CDC: ${sfcdc}"
cap lab var note_sfvillage "Village: ${sfvillage}"
cap lab var note_sfcbsg_name "Name of CBSG: ${sfcbsg}"
cap lab var note_sfnumber1 "Mobile number: ${sfnumber1}"
cap lab var note_sfnumber2 "Alt mobile number: ${sfnumber2}"
cap lab var note_sfnumber3 "2nd Alt mobile number: ${sfnumber3}"
cap lab var enum_name1 "Name of Enumerator for CBSG respondent survey"
cap lab var enum_name2 "Name of Enumerator for MKP survey"
cap lab var cbsg_started "For enumerator: Has introductory module been completed for CBSG participant?"
cap lab var order "For enumerator: Please completed introductory module of CBSG survey, and then begin this survey"
cap lab var resp_ver "For enumerator: Is ${sfcbsg_resp} the correct name of the CBSG member residing in this household?"
cap lab var resp_corr "For enumerator: Please write name of CBSG member/respondent, and be careful about spelling"
cap lab var cbsg_resp "Name of CBSG respondent"
cap lab var mod1 "intro"
cap lab var Q1k "We are a team working with the Aga Khan Foundation and the World Bank. We are working on a project concerned with developing local economies. The results of the survey will be important for helping design programs on local economic development for the People of Afghanistan. The interview will take about 60 minutes. All the information we obtain will remain strictly confidential and your answers will never be identified. Do we have your consent to complete the interview?"
cap lab var Q1k_whynot "Why not?"
cap lab var Q1k2_other "Specify other reason"
cap lab var Q1l_date "When should we come back?"
cap lab var Q1l_time "What time of day is best?"
cap lab var Q1m3_0 "Do you have a contact number?"
cap lab var Q1m3 "Mobile number"
cap lab var Q1m4_0 "Does anyone else in your household have a contact number?"
cap lab var Q1m4 "Q1i2 Family member mobile number"
cap lab var Q1m5_0 "Do you have an alternative contact number?"
cap lab var Q1m5 "Q1i3 Alternative mobile number"
cap lab var Q1m_note "You must list at least one phone number for household"
cap lab var mod2 "2. HH Roster"
cap lab var note1 "We would like to start with some information about the people who usually live and sleep in this household, starting with the head of the household. Please mention all people who usually stay here, including babies and infants, and people who are not immediate kin."
cap lab var note2 "A household is defined as a group of people who normally live together and eat meals together, and have been doing so for at least 6 of the 12 months preceding the interview. Therefore, a member of your household is defined on the basis of the usual place of residence, and short term guests are not included. PLEASE NOTE that in this list, The following categories of people are considered as household members even though they have lived for less than 6 months in the past 12 months: (i) Infants who are less than 6 months old (ii) Newly married who have been living together for less than 6 months (iii) Students and seasonal workers who have not been living in or as part of another household, and (iv) Other persons living together for less than 6 months but who are expected to live in the household permanently (or for a longer duration). Servants, farm workers and other such individuals who live and take meals with the household are to be identified as household members, even though they may not have blood relationship with the respondent."
cap lab var Q2a "According to this definition of a household, how many individuals live in the household?"
cap lab var members "Roster 1: List of members"
cap lab var Q2_memberid "ID for household member"
cap lab var Q2b "Name of household member"
cap lab var Q2c "Is this member usually present in the household (and not part of another household)?"
cap lab var Q2c_other "Other (please Specify)?"
cap lab var Q2d "What is ${Q2b}'s age in completed years?"
cap lab var Q2c_month "What is ${Q2b}'s age in completed Months?"
cap lab var members "Roster 1 hh members"
cap lab var det "Roster 2"
cap lab var roster2_res "Roster residents"
cap lab var rost2 "Roster 2: Details"
cap lab var roster2_name "Roster2 name"
cap lab var roster2_age "Roster2 age"
cap lab var roster2note "I will now ask you a questions about ${roster2_name}, age ${roster2_age}"
cap lab var Q2g "What is the relationship of ${roster2_name} to you?"
cap lab var Q2g_other "Other (please Specify)?"
cap lab var Q2h "Is ${roster2_name} male or female?"
cap lab var Q2i "What is the marital status of ${roster2_name}?"
cap lab var Q2j "Does ${roster2_name} have a tazkira?"
cap lab var Q2k1 "Did ${roster2_name} reside outside of the home for more than 3 months of the past 12 months?"
cap lab var Q2k2 "Where does ${roster2_name} go?"
cap lab var Q2k2_other "Other (please Specify)?"
cap lab var Q2l "Can ${roster2_name} read and write?"
cap lab var Q2m "Did ${roster2_name} ever attend formal school? (including formal Islamic school)"
cap lab var Q2n1 "What is the highest grade in which ${roster2_name} was enrolled?"
cap lab var Q2n1_error "You stated that ${roster2_name} never attended school, but then indicated that ${roster2_name} attended some schooling in the next question. Please clarify"
cap lab var Q2n2 "Enter highest grade level COMPLETED"
cap lab var Q2o1 "How many days was ${roster2_name}'s school in session over the past 2 weeks?"
cap lab var Q2o2 "How many days did ${roster2_name} attend school in the past 2 weeks?"
cap lab var Q2q "In the past SEVEN DAYS how many TOTAL HOURS did ${roster2_name} work on household chores, or tending to children, cooking, fetching water, or other household chores?"
cap lab var Q2r "In the past SEVEN DAYS, did ${roster2_name} do any work for pay, for profit, or for family gain, INCLUDING farm work or tending livestock, or poultry, or any occasional work, EVEN for one hour?"
cap lab var Q2s "Although ${roster2_name} did not work last week, does he/she have work from which he/she was temporarily absent?"
cap lab var Q2t "What are the main reasons that ${roster2_name} did not work in the last seven days?"
cap lab var Q2t_other "Other Specify"
cap lab var Q2u "What kinds of work (paid or unpaid) was ${roster2_name}'s biggest sources of income over the past 12 MONTHS (Select all that apply in the past 12 MONTHS, up to 3)"
cap lab var Q2u_other "Other (please Specify)?"
cap lab var Q2v "What is the total amount in cash, services or goods ${roster2_name} received for ALL OF THESE economic activities in the last 30 DAYS, if any? (in case of cash include any bonuses, commissions, allowances or tips)"
cap lab var Q2_roster_act_id "Roster activity ID"
cap lab var Q2_roster_act_name "Roster activity label"

*> start manual labelling
cap lab var Q2w1 "I will now ask you 5 questions about (${Q2_roster_act_name}), the activity that you mentioned above. How many DAYS did ${roster2_name} work in this activity during the past SEVEN DAYS?"
cap lab var Q2w2 "How many actual HOURS PER DAY, on average, did ${roster2_name} work on average on this activity  (${Q2_roster_act_name}) during the past SEVEN DAYS?"
cap lab var Q2w3 "Did ${roster2_name}'s work on this activity  (${Q2_roster_act_name}) take place INSIDE the household or household land?"
cap lab var Q2w4 "Did ${roster2_name} receive any payment in cash or in-kind for their work on ${Q2_roster_act_name}"
cap lab var Q2w5 "What is ${roster2_name} relationship's with this employer for their work in (${Q2_roster_act_name})?"
cap lab var Q2w5_other "Other (please Specify)?"
cap lab var Q2_estimate "Please estimate the total income for your entire household combined over the last 30 DAYS"
*< end manual labelling

cap lab var Q2x1 "remittances from those who do not live in the household?"
cap lab var Q2x2 "income from lending funds to others?"
cap lab var Q2x3 "rental income?"
cap lab var Q2x4 "income from pensions?"
cap lab var Q2x5 "income from zakat?"
cap lab var Q2x6 "other income not yet discussed?"

*> start manual labelling
*cap lab var roster2_name1 "Roster2 name1"
*cap lab var roster2_name2 "Roster2 name2"
*cap lab var roster2_name3 "Roster2 name3"
*cap lab var roster2_name4 "Roster2 name4"
*cap lab var roster2_name5 "Roster2 name5"
*cap lab var roster2_name6 "Roster2 name6"
*cap lab var roster2_name7 "Roster2 name7"
*cap lab var roster2_name8 "Roster2 name8"
*cap lab var roster2_name9 "Roster2 name9"
*cap lab var roster2_name10 "Roster2 name10"
*cap lab var roster2_name11 "Roster2 name11"
*cap lab var roster2_name12 "Roster2 name12"
*cap lab var roster2_name13 "Roster2 name13"
*cap lab var roster2_name14 "Roster2 name14"
*cap lab var roster2_name15 "Roster2 name15"
*cap lab var roster2_name16 "Roster2 name16"
*cap lab var roster2_name17 "Roster2 name17"
*cap lab var roster2_name18 "Roster2 name18"
*cap lab var roster2_name19 "Roster2 name19"
*cap lab var roster2_name20 "Roster2 name20"
*cap lab var roster2_age1 "Roster2 name1"
*cap lab var roster2_age2 "Roster2 name2"
*cap lab var roster2_age3 "Roster2 name3"
*cap lab var roster2_age4 "Roster2 name4"
*cap lab var roster2_age5 "Roster2 name5"
*cap lab var roster2_age6 "Roster2 name6"
*cap lab var roster2_age7 "Roster2 name7"
*cap lab var roster2_age8 "Roster2 name8"
*cap lab var roster2_age9 "Roster2 name9"
*cap lab var roster2_age10 "Roster2 name10"
*cap lab var roster2_age11 "Roster2 name11"
*cap lab var roster2_age12 "Roster2 name12"
*cap lab var roster2_age13 "Roster2 name13"
*cap lab var roster2_age14 "Roster2 name14"
*cap lab var roster2_age15 "Roster2 name15"
*cap lab var roster2_age16 "Roster2 name16"
*cap lab var roster2_age17 "Roster2 name17"
*cap lab var roster2_age18 "Roster2 name18"
*cap lab var roster2_age19 "Roster2 name19"
*cap lab var roster2_age20 "Roster2 name20"
*< end manual labelling

cap lab var mod3 "3. HH Dynamics"
cap lab var Q3a0 "I will now ask you a few questions about household decision making"
cap lab var Q3a_list "list of members"
cap lab var Q3a "The head of the household is a person among the group of householders who is regarded/assigned as the head of the household and generally makes decisions in the household. Which individual listed is the head of household?"

*> start manual labelling
*cap lab var Q3a_name1 "${roster2_name1}, age ${roster2_age1}"
*cap lab var Q3a_name2 "${roster2_name2}, age ${roster2_age2}"
*cap lab var Q3a_name3 "${roster2_name3}, age ${roster2_age3}"
*cap lab var Q3a_name4 "${roster2_name4}, age ${roster2_age4}"
*cap lab var Q3a_name5 "${roster2_name5}, age ${roster2_age5}"
*cap lab var Q3a_name6 "${roster2_name6}, age ${roster2_age6}"
*cap lab var Q3a_name7 "${roster2_name7}, age ${roster2_age7}"
*cap lab var Q3a_name8 "${roster2_name8}, age ${roster2_age8}"
*cap lab var Q3a_name9 "${roster2_name9}, age ${roster2_age9}"
*cap lab var Q3a_name10 "${roster2_name10}, age ${roster2_age10}"
*cap lab var Q3a_name11 "${roster2_name11}, age ${roster2_age11}"
*cap lab var Q3a_name12 "${roster2_name12}, age ${roster2_age12}"
*cap lab var Q3a_name13 "${roster2_name13}, age ${roster2_age13}"
*cap lab var Q3a_name14 "${roster2_name14}, age ${roster2_age14}"
*cap lab var Q3a_name15 "${roster2_name15}, age ${roster2_age15}"
*cap lab var Q3a_name16 "${roster2_name16}, age ${roster2_age16}"
*cap lab var Q3a_name17 "${roster2_name17}, age ${roster2_age17}"
*cap lab var Q3a_name18 "${roster2_name18}, age ${roster2_age18}"
*cap lab var Q3a_name19 "${roster2_name19}, age ${roster2_age19}"
*cap lab var Q3a_name20 "${roster2_name20}, age ${roster2_age20}"
*< end manual labelling

*> start manual labelling
cap lab var Q3b "Does the head of household do any of the following (select all that apply)?"
*< end manual labelling

cap lab var Q3b_other "Other (please Specify)?"
cap lab var Q3c_list "list of members"
cap lab var Q3c "Which individual listed is {$cbsg_resp}?"

*> start manual labelling
*cap lab var Q3c_name1 "${roster2_name1}, age ${roster2_age1}"
*cap lab var Q3c_name2 "${roster2_name2}, age ${roster2_age2}"
*cap lab var Q3c_name3 "${roster2_name3}, age ${roster2_age3}"
*cap lab var Q3c_name4 "${roster2_name4}, age ${roster2_age4}"
*cap lab var Q3c_name5 "${roster2_name5}, age ${roster2_age5}"
*cap lab var Q3c_name6 "${roster2_name6}, age ${roster2_age6}"
*cap lab var Q3c_name7 "${roster2_name7}, age ${roster2_age7}"
*cap lab var Q3c_name8 "${roster2_name8}, age ${roster2_age8}"
*cap lab var Q3c_name9 "${roster2_name9}, age ${roster2_age9}"
*cap lab var Q3c_name10 "${roster2_name10}, age ${roster2_age10}"
*cap lab var Q3c_name11 "${roster2_name11}, age ${roster2_age11}"
*cap lab var Q3c_name12 "${roster2_name12}, age ${roster2_age12}"
*cap lab var Q3c_name13 "${roster2_name13}, age ${roster2_age13}"
*cap lab var Q3c_name14 "${roster2_name14}, age ${roster2_age14}"
*cap lab var Q3c_name15 "${roster2_name15}, age ${roster2_age15}"
*cap lab var Q3c_name16 "${roster2_name16}, age ${roster2_age16}"
*cap lab var Q3c_name17 "${roster2_name17}, age ${roster2_age17}"
*cap lab var Q3c_name18 "${roster2_name18}, age ${roster2_age18}"
*cap lab var Q3c_name19 "${roster2_name19}, age ${roster2_age19}"
*cap lab var Q3c_name20 "${roster2_name20}, age ${roster2_age20}"
*< end manual labelling

cap lab var marstatus "What is the marital status of ${cbsg_resp}?"
cap lab var Q3d_list "list of members"
cap lab var Q3d "Which individual(s) listed is the spouse of {$cbsg_resp}?"
cap lab var Q3d_na "Do not have a spouse"

*> start manual labelling
*cap lab var Q3d_name1 "${roster2_name1}, age ${roster2_age1}"
*cap lab var Q3d_name2 "${roster2_name2}, age ${roster2_age2}"
*cap lab var Q3d_name3 "${roster2_name3}, age ${roster2_age3}"
*cap lab var Q3d_name4 "${roster2_name4}, age ${roster2_age4}"
*cap lab var Q3d_name5 "${roster2_name5}, age ${roster2_age5}"
*cap lab var Q3d_name6 "${roster2_name6}, age ${roster2_age6}"
*cap lab var Q3d_name7 "${roster2_name7}, age ${roster2_age7}"
*cap lab var Q3d_name8 "${roster2_name8}, age ${roster2_age8}"
*cap lab var Q3d_name9 "${roster2_name9}, age ${roster2_age9}"
*cap lab var Q3d_name10 "${roster2_name10}, age ${roster2_age10}"
*cap lab var Q3d_name11 "${roster2_name11}, age ${roster2_age11}"
*cap lab var Q3d_name12 "${roster2_name12}, age ${roster2_age12}"
*cap lab var Q3d_name13 "${roster2_name13}, age ${roster2_age13}"
*cap lab var Q3d_name14 "${roster2_name14}, age ${roster2_age14}"
*cap lab var Q3d_name15 "${roster2_name15}, age ${roster2_age15}"
*cap lab var Q3d_name16 "${roster2_name16}, age ${roster2_age16}"
*cap lab var Q3d_name17 "${roster2_name17}, age ${roster2_age17}"
*cap lab var Q3d_name18 "${roster2_name18}, age ${roster2_age18}"
*cap lab var Q3d_name19 "${roster2_name19}, age ${roster2_age19}"
*cap lab var Q3d_name20 "${roster2_name20}, age ${roster2_age20}"
*< end manual labelling

cap lab var parstatus "Does ${cbsg_resp} have children?"
cap lab var Q3e_list "list of members"
cap lab var Q3e "Which individual(s) listed are the biological children of {$cbsg_resp}?"
cap lab var Q3e_na "Do not have any children"
cap lab var Q3e_name1 "${roster2_name1}, age ${roster2_age1}"
cap lab var Q3e_name2 "${roster2_name2}, age ${roster2_age2}"
cap lab var Q3e_name3 "${roster2_name3}, age ${roster2_age3}"
cap lab var Q3e_name4 "${roster2_name4}, age ${roster2_age4}"
cap lab var Q3e_name5 "${roster2_name5}, age ${roster2_age5}"
cap lab var Q3e_name6 "${roster2_name6}, age ${roster2_age6}"
cap lab var Q3e_name7 "${roster2_name7}, age ${roster2_age7}"
cap lab var Q3e_name8 "${roster2_name8}, age ${roster2_age8}"
cap lab var Q3e_name9 "${roster2_name9}, age ${roster2_age9}"
cap lab var Q3e_name10 "${roster2_name10}, age ${roster2_age10}"
cap lab var Q3e_name11 "${roster2_name11}, age ${roster2_age11}"
cap lab var Q3e_name12 "${roster2_name12}, age ${roster2_age12}"
cap lab var Q3e_name13 "${roster2_name13}, age ${roster2_age13}"
cap lab var Q3e_name14 "${roster2_name14}, age ${roster2_age14}"
cap lab var Q3e_name15 "${roster2_name15}, age ${roster2_age15}"
cap lab var Q3e_name16 "${roster2_name16}, age ${roster2_age16}"
cap lab var Q3e_name17 "${roster2_name17}, age ${roster2_age17}"
cap lab var Q3e_name18 "${roster2_name18}, age ${roster2_age18}"
cap lab var Q3e_name19 "${roster2_name19}, age ${roster2_age19}"
cap lab var Q3e_name20 "${roster2_name20}, age ${roster2_age20}"
cap lab var Q3f_list "list of members"
cap lab var Q3f "Which individual(s) listed are currently members of any CBSGs?"
cap lab var Q3f_na "No others are members of any CBSG"
cap lab var Q3f_name1 "${roster2_name1}, age ${roster2_age1}"
cap lab var Q3f_name2 "${roster2_name2}, age ${roster2_age2}"
cap lab var Q3f_name3 "${roster2_name3}, age ${roster2_age3}"
cap lab var Q3f_name4 "${roster2_name4}, age ${roster2_age4}"
cap lab var Q3f_name5 "${roster2_name5}, age ${roster2_age5}"
cap lab var Q3f_name6 "${roster2_name6}, age ${roster2_age6}"
cap lab var Q3f_name7 "${roster2_name7}, age ${roster2_age7}"
cap lab var Q3f_name8 "${roster2_name8}, age ${roster2_age8}"
cap lab var Q3f_name9 "${roster2_name9}, age ${roster2_age9}"
cap lab var Q3f_name10 "${roster2_name10}, age ${roster2_age10}"
cap lab var Q3f_name11 "${roster2_name11}, age ${roster2_age11}"
cap lab var Q3f_name12 "${roster2_name12}, age ${roster2_age12}"
cap lab var Q3f_name13 "${roster2_name13}, age ${roster2_age13}"
cap lab var Q3f_name14 "${roster2_name14}, age ${roster2_age14}"
cap lab var Q3f_name15 "${roster2_name15}, age ${roster2_age15}"
cap lab var Q3f_name16 "${roster2_name16}, age ${roster2_age16}"
cap lab var Q3f_name17 "${roster2_name17}, age ${roster2_age17}"
cap lab var Q3f_name18 "${roster2_name18}, age ${roster2_age18}"
cap lab var Q3f_name19 "${roster2_name19}, age ${roster2_age19}"
cap lab var Q3f_name20 "${roster2_name20}, age ${roster2_age20}"
cap lab var Q3g "Who has the final say on Purchasing food for the family of ${cbsg_resp}"
cap lab var Q3h "Who has the final say on Whether the family of ${cbsg_resp} may borrow funds"
cap lab var Q3i "Who has the final say on Purchase of assets that ${cbsg_resp}'s family uses"
cap lab var mod4 "4. Consumption"
cap lab var Q4a "Now, imagine that you have an emergency and you need to pay AFG 2060. How possible is it that you could come up with AFG 2060 within the NEXT MONTH? Is it very possible, somewhat possible, not very possible, or not at all possible?"
cap lab var exp3 "Expenditure past 3 months"
cap lab var Q4b0 "I will now ask you about your household's expenditure. In the past 3 months, how much did your household spend on..."
cap lab var Q4b1 "Health services and medicines"
cap lab var Q4b2 "Tuition for education"
cap lab var Q4b3 "Other education expenses (uniforms, textbooks, school supplies)"
cap lab var exp1 "Expenditure past 1 month"
cap lab var Q4b_1mo_note "In the past month, how much did your household spend on the following categories of items:"
cap lab var Q4b4 "Food at home"
cap lab var Q4b5 "Food away from home"
cap lab var Q4b6 "Grooming, cosmetics, laundry, soap, shampoo (hygiene)"
cap lab var Q4b7 "Housing rent"
cap lab var Q4b8 "Communication (phone & internet)"
cap lab var Q4b9 "Transportation"
cap lab var Q4c "During the last 12 MONTHS did you always have enough food for your household?"
cap lab var Q4d "Q4d For how many months in the last 12 months did you not have enough food for your household?"
cap lab var Q4d1 "In the past seven days, has there been any time when your household did not have enough food or money to buy food?"
cap lab var food "Food"
cap lab var Q4d_note "In the past seven days, when you did not have enough food or money…"
cap lab var Q4d2 "HOW OFTEN did anyone in your household have to: rely on less-preferred and less-expensive foods because of lack of resources?"
cap lab var Q4d3 "HOW OFTEN did anyone in your household have to:  limit portion sizes at meal times?"
cap lab var Q4d4 "HOW OFTEN did anyone in your household have to:  restrict consumption by adults in order for small children to eat?"
cap lab var Q4d5 "HOW OFTEN did anyone in your household have to:  skip meals or reduce number of meals eaten by anyone in household?"
cap lab var diet "Diet"
cap lab var Q4e0 "I will now ask you about your household's consumption of the following food groups. How many days in the past 7 days did your entire household eat:"
cap lab var Q4e1 "Cereals (e.g. bread, wheat, rice, maize, pasta, etc.)"
cap lab var Q4e2 "Tubers (e.g. potatoes, sweet potatoes, etc.)"
cap lab var Q4e3 "Pulses and nuts (e.g. beans, lentils, peas, peanuts, etc.)"
cap lab var Q4e4 "Vegetables (e.g. onion, tomato, eggplant, cabbage, etc.)"
cap lab var Q4e5 "Fruits (e.g. water melon, apricots, grapes, raisins, etc.)"
cap lab var Q4e6 "Meat and fish of all types, eggs"
cap lab var Q4e7 "Dairy and dairy products (e.g. milk, yoghurt, krut, dogh, cheese, other milk products)"
cap lab var Q4e8 "Sugar, honey"
cap lab var Q4e9 "Oils, fats"
cap lab var mod5 "5.Assets"
cap lab var Q5a "What type of dwelling best describes your current dwelling?"
cap lab var Q5a_other "Other (please Specify)?"
cap lab var Q5b "How many years ago was this dwelling constructed?"
cap lab var Q5c "What is the arrangement on the basis of which your household occupies this dwelling"
cap lab var Q5other "Other (please Specify)?"
cap lab var Q5d "If you were to purchase this dwelling today, how much would it cost?"
cap lab var Q5e "What is the distance to this dwelling from the nearest paved road? (in meters)"
cap lab var Q5f1 "Has your household had electricity at any time in the past 30 DAYS from any of these sources: Electric grid or Government generator"
cap lab var Q5f2 "Has your household had electricity at any time in the past 30 DAYS from any of these sources: Private generator"
cap lab var Q5f3 "Has your household had electricity at any time in the past 30 DAYS from any of these sources: Community generator"
cap lab var Q5f4 "Has your household had electricity at any time in the past 30 DAYS from any of these sources: Other sources"

*> start manual labelling
*cap lab var Q5g "What is the main source of heating for his house in the winter?"
*< end manual labelling

cap lab var Q5g_other "Other (please Specify)?"
cap lab var Q5h "Which main toilet facility does your household use?"
cap lab var Q5h_other "Other (please Specify)?"
cap lab var Q5i "Is the toilet facility shared with other households?"

*> start manual labelling
cap lab var Q5j1 "What has been the main source of drinking water for your household in the past 30 days? Piped - private"
cap lab var Q5j2 "What has been the main source of drinking water for your household in the past 30 days? Piped - municipal"
cap lab var Q5j3 "What has been the main source of drinking water for your household in the past 30 days? Hand pump (bore hole, tube well)-private"
cap lab var Q5j4 "What has been the main source of drinking water for your household in the past 30 days? Hand pump (bore hole, tube well)-public"
cap lab var Q5j5 "What has been the main source of drinking water for your household in the past 30 days? Spring, well or kariz - protected"
cap lab var Q5j6 "What has been the main source of drinking water for your household in the past 30 days? Spring, well or kariz - uprotected"
cap lab var Q5j7 "What has been the main source of drinking water for your household in the past 30 days? Surface water (river, stream, irrigation, channel, lake, pond, kanda)"
cap lab var Q5j8 "What has been the main source of drinking water for your household in the past 30 days? Tanker-truck"
cap lab var Q5j96 "What has been the main source of drinking water for your household in the past 30 days? Other"
cap lab var Q5j98 "What has been the main source of drinking water for your household in the past 30 days? Do not know"
cap lab var Q5j99 "What has been the main source of drinking water for your household in the past 30 days? Refuse to answer"
*< end manual labelling

cap lab var Q5j_other "Other (please Specify)?"
cap lab var Q5k "How many minutes does it take to walk, one way, to this main source of water in warm season?"
cap lab var Q5l "What is the main phone service that you use?"
cap lab var Q5l_other "Other (please Specify)?"
cap lab var Q5m1 "Do any of your household members own agricultural land or a garden plot?"
cap lab var Q5m2 "How many Jeribs of agricultural land in total does your household own?"
cap lab var Q5m3 "How many jeribs of irrigated land without garden plot did you or a member of your household own in the most recent spring cultivation season?"
cap lab var Q5m4 "If you were to sell this plot of land today, how much could you sell it for?"
cap lab var Q5m5 "How many jeribs of rain-fed land without garden plot did you or a member of your household own in the most recent spring cultivation season?"
cap lab var Q5m6 "If you were to sell this land today, how much could you sell it for?"
cap lab var Q5m7 "How many jeribs of garden plot did you or a member of your household own in the most recent spring cultivation season?"
cap lab var Q5m8 "If you were to sell this plot of land today, how much could you sell it for?"
cap lab var Q5m9 "Does your household currently own any land or buildings (do not include residential property which your household occupies or agricultural land or property used by your household which was reported above)?"
cap lab var Q5m10 "How much money would your household receive if you sold all this property today?"

*> start manual labelling
cap lab var Q5assets "Do you have any of the following assets?"
*< end manual labelling

cap lab var Q5assets_other "Other (please Specify)?"

*> start manual labelling
cap lab var asset_id "asset id"
cap lab var asset_name "asset name"
cap lab var Q5asset1_1 "How many ${asset_name} does your household own today?"
cap lab var Q5asset1_2 "If you sold one of your ${asset_name} today, how much money could you get for it?"
*< end manual labelling

cap lab var Q10a "In the last 30 days, that is, the last one month, how many days did you attend any kind of group meeting with members of your community?"
cap lab var Q10a1 "During those meetings, how often did you speak such that everyone at the meeting could hear you?"
cap lab var Q10b "Did you attend any CDC/village meetings in the last 12 MONTHS?"
cap lab var Q10c "Are you a leader in your community, school, mosque, or in any groups?"
cap lab var howtrue "how true"
cap lab var Q10d_note "Is each statement Never True, Not very true, Somewhat true, or Always true:"
cap lab var Q10d "My actions on what types of work I do are determined by the situation. I don’t really have an option."
cap lab var Q10e "My actions in what types of work I do are partly because I will get in trouble with someone if I act differently."
cap lab var Q10f "Regarding the types of work I do, I do what I do so others don’t think poorly of me."
cap lab var Q10g "Regarding the types of work I do, I do what I do because I personally think it is the right thing to do."
cap lab var Q10h1 "How much would ${cbsg_resp}'s opinion be considered in the final decision if your household needs to decide on the following things:"
cap lab var Q10h2 "Buying groceries"
cap lab var Q10h3 "Buying expensive items (i.e. mobile phone, farm equipment)"
cap lab var Q10h4 "Buying or selling land or property"
cap lab var Q10h5 "Whether his/her daughter should attend school"
cap lab var Q10h6 "Whether his/her son should attend school"
cap lab var Q10h7 "Marriage of his/her children"
cap lab var Q10h8 "How many children he/she has"
cap lab var Q10h9 "He/she wanted to pursue a job outside the home"
cap lab var Q10i1 "How much input does ${cbsg_resp} have in making decisions about INCOME HE/SHE EARNS?"
cap lab var Q10i2 "When decisions are made regarding  INCOME ${cbsg_resp} EARNS, who is it that normally takes the decision?"
cap lab var Q10i3 "To what extent do you feel ${cbsg_resp} can make his/her own personal decisions regarding  INCOME HE/SHE EARNS if HE/SHE want(ed) to?"
cap lab var Q10j1 "How much input does ${cbsg_resp} have in making decisions about HOW HOUSEHOLD INCOME IS SPENT?"
cap lab var Q10j2 "When decisions are made regarding  HOW HOUSEHOLD INCOME IS SPENT, who is it that normally takes the decision?"
cap lab var Q10j3 "To what extent do you feel ${cbsg_resp} can make his/her own personal decisions regarding  HOW HOUSEHOLD INCOME IS SPENT if he/she want(ed) to?"
cap lab var Q10k1 "How much input does ${cbsg_resp} have in making decisions about WHICH BUSINESS OPPORTUNITIES TO PURSUE?"
cap lab var Q10k2 "When decisions are made regarding WHICH BUSINESS OPPORTUNITIES TO PURSUE, who is it that normally takes the decision?"
cap lab var Q10k3 "To what extent do you feel ${cbsg_resp} can make his/her own personal decisions on WHICH BUSINESS OPPORTUNITIES TO PURSUE if he/she want(ed) to?"
cap lab var Q10l1 "How much input does ${cbsg_resp} have in making decisions about PURCHASING MATERIALS FOR HIS/HER BUSINESS?"
cap lab var Q10l2 "When decisions are made regarding PURCHASING MATERIALS FOR ${cbsg_resp}'s BUSINESS, who is it that normally takes the decision?"
cap lab var Q10l3 "To what extent do you feel ${cbsg_resp} can make his/her own personal decisions on PURCHASING MATERIALS FOR YOUR BUSINESS if he/she want(ed) to?"
cap lab var Q10m1 "How much do you agree or disagree with the following statement: The important decisions in the family should be made only by the men of the family."
cap lab var Q10m2 "How much do you agree or disagree with the following statement: If the wife is working outside the home, then the husband should help her with the household chores."
cap lab var Q10m3 "How much do you agree or disagree with the following statement: A married woman should be allowed to work outside the home if she wants to."
cap lab var Q10m4 "How much do you agree or disagree with the following statement: A wife should tolerate being beaten by her husband in order to keep the family together."
cap lab var Q10m5 "How much do you agree or disagree with the following statement: It is better to send a son to school than it is to send a daughter."
cap lab var Q10m6 "How much do you agree or disagree with the following statement: The wife has a right to express her opinion even if she disagrees with what her husband is saying"
cap lab var text13 "End of the survey for the interviewee. Please thank them for their time."
cap lab var gps "Record GPS"
cap lab var Q99a "Q99a) Interview language"
cap lab var Q99a_other "Other (Please Spicify)"
cap lab var Q99b "Q99b) Interview status"
cap lab var Q99c "Q99c) On a scale of 1 (poorest) to 10 (wealthiest), how wealthy do you think the respondent's household is in comparison with other households in the village/community?"
cap lab var Q99d "Q99d) How was the degree of co-operation of the respondent?"
cap lab var Q99e "Q99e) During the interview of the respondent, was anyone else in listening?"
cap lab var Q99e1 "Q99e1) Do you think the presence of another person influenced the answers of the respondent?"
cap lab var Q99f "Q99f) If no GPS Coordinates can be collected, mark down the address of the household, or a description and landmarks for relocating."
cap lab var Q99g "Q99g) Please record any general notes about the interview and any special information that will be helpful for supervisors, office editors, and data analysis."
